### ISSUE TITLE
Problems switching to alpine based images: non-consistent uid for www-data

### ISSUE THREAD

**Issue by NandoTheessen** [docker-library/php#1010]
We ran into this when switching over to alpine based images.
The uid for the user www-data is different for the debian base & the alpine base.

This lead to crashes for us because the log-files we use where chowned to a different uid.

Happy to put in a PR if this is a change the maintainers would like to make.

**Comment by wglambert** [comment]
https://github.com/docker-library/php/blob/d41f0d0c2a71b16280e5c26d06570bf7d76f3621/7.4/alpine3.11/fpm/Dockerfile#L31-L38

You could try running as an arbitrary user/UID https://github.com/docker-library/docs/tree/master/php#running-as-an-arbitrary-user

**Comment by FabianKoestring** [comment]
Having the same Problem using `nginx:1.16.1-alpine` and `php:7.4.7-fpm-buster`. We set `RUN addgroup www-data xfs` in our Nginx Dockerfile.....

**Comment by yosifkit** [comment]
For Alpine vs Debian, we use the standard uid/gid that each has chosen for their OS.

If you need two containers to be running as the same user, then have the orchestration run them via a number rather than a name or you have to make sure the name that you choose has the same number. (Alternatively, some orchestrators use a group number to ensure access between related containers.)

Most official images are designed such that you can run them as whatever user id you want. For services needing a low port, you may currently run into https://github.com/moby/moby/issues/8460 and need to wait for a Docker release with https://github.com/moby/moby/pull/41030 or add `--sysctl net.ipv4.ip_unprivileged_port_start=0`.
