### ISSUE TITLE
CVE-2020-11655 - sqlite vulnerability being detected via trivy

### ISSUE THREAD

**Issue by TomTucka** [docker-library/php#1016]
Hey Team 👋 

We run trivy in our automated CI/CD process, and we noticed its detecting a medium severity issue with sqlite.

```
php:7.4-fpm-alpine3.11 (alpine 3.11.6)
======================================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)

+---------+------------------+----------+-------------------+---------------+--------------------------------+
| LIBRARY | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |             TITLE              |
+---------+------------------+----------+-------------------+---------------+--------------------------------+
| sqlite  | CVE-2020-11655   | MEDIUM   | 3.30.1-r1         | 3.30.1-r2     | sqlite: malformed              |
|         |                  |          |                   |               | window-function query leads to |
|         |                  |          |                   |               | DoS                            |
+---------+------------------+----------+-------------------+---------------+--------------------------------+

```

Are you planning to fix this issue within the `php:7.4-fpm-alpine3.11` image? 

EDIT: I have rebuilt the container locally and this does fix this issue

**Comment by yosifkit** [comment]
This was addressed in Alpine just 6 days ago (https://gitlab.alpinelinux.org/alpine/aports/-/issues/11508).

From our [FAQ](https://github.com/docker-library/faq/#why-does-my-security-scanner-show-that-an-image-has-cves):

> We strive to publish updated images at least monthly for Debian and Ubuntu. We also rebuild earlier if there is a critical security need, e.g. docker-library/official-images#2171. Many Official Images are maintained by the community or their respective upstream projects, like Alpine and Oracle Linux, and are subject to their own maintenance schedule.

We only rebuild images if their base image is updated or if they are updated (Dockerfile changes) and make heavy use of Docker build cache so that users aren't subject to excessive image churn for no reason.

Given that there were PHP releases just yesterday, this should be fixed when the bump happens here (since [sqlite](https://github.com/docker-library/php/blob/f6170fb3db7826cb8e67b4a8dc56602c1a163a97/7.4/alpine3.11/fpm/Dockerfile#L112) is added to the image after the version `ENV`). The automated `update.sh` will do the bump as soon as they are available on https://www.php.net/releases/. See [here](https://github.com/docker-library/faq/#an-images-source-changed-in-git-now-what) for the full process to how it will be available via `docker pull`.
