### ISSUE TITLE
Install Certbot on this image

### ISSUE THREAD

**Issue by kpeter477** [docker-library/php#1045]
I tried to install Certbot in the dockerfile in several ways, but always error is the end. You use debian like commands, but it cant find wget, etc. Could you please show a way to do it? On Certbot website, there are install instructions for various OSs.

**Comment by phy25** [comment]
> it cant find wget

`apt install wget`

**Comment by wglambert** [comment]
What's your Dockerfile or what commands are you running, and what error are you getting?

Here's an example Dockerfile for installing packages in Debian containers
```dockerfile
FROM php

RUN apt update && apt install -y --no-install-recommends certbot && \
  rm -rf /var/lib/apt/lists/*
```

This is the package and version from Debian Buster's repository https://packages.debian.org/buster/certbot

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
