### ISSUE TITLE
GPIO - Access

### ISSUE THREAD

**Issue by DonMaverick** [docker-library/php#1056]
Hello together,

I use your image on various Raspberrys.
After an update the Python "import RPi.GPIO as GPIO" seems to have changed.

Now I get an error message in your container when I execute my script
"RuntimeError: This module can only be run on a Raspberry Pi! "

Do you have an idea? How I can control my GPIOs from your image / container against my GPIOs?

Best regards

Info:
FROM php:7.2-apache

docker run -d -p 80:80 --restart always -v ~/Container_PI_Garten/daten:/var/www/html --privileged --device=/dev/bus/usb/001/003 --device=/dev/gpiomem --name pi pi

**Comment by wglambert** [comment]
Could you show the log output, and which Pi are you using?

**Comment by DonMaverick** [comment]
It is a RP4

......
root@5bdeaef09a47:/var/www/html# ls -l
4total 32
-rw-r--r-- 1 1000 1000  547 Sep 10 15:25 index.html
-rw-r--r-- 1 1000 1000 1396 Sep 10 15:25 main.html
-rwxr-xr-x 1 1000 1000 3951 Sep 10 15:25 main.php
-rwxr-xr-x 1 1000 1000   33 Sep 10 15:25 status.csv
-rwxr-xr-x 1 1000 1000 1545 Sep 10 15:25 status.py
-rwxr-xr-x 1 1000 1000  503 Sep 10 15:25 strom0.py
-rwxr-xr-x 1 1000 1000  615 Sep 10 15:25 strom1.py
-rwxr-xr-x 1 1000 1000  519 Sep 10 15:25 strom_boot.py

root@5bdeaef09a47:/var/www/html# python strom_boot.py 
Traceback (most recent call last):
  File "strom_boot.py", line 4, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python2.7/dist-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
root@5bdeaef09a47:/var/www/html#

**Comment by yosifkit** [comment]
Since the Dockerfile for the `php:7.2-apache` has been [unchanged for the past 25 days](https://github.com/docker-library/php/blob/165f8ca09cbbe90f22566c6ad6b18a284b77bb7e/7.2/buster/apache/Dockerfile), the only other change that could affect it would be the [rebuild of Debian](https://github.com/docker-library/official-images/pull/8696) (which then causes rebuilds of all dependent images in order to get things like security updates). 

I assume you are just `apt-get install`ing some things and perhaps a `pip install`, so, I would guess that one of the following: python and/or pip updates in Debian packages have changes that don't work with your python libraries; or that your libraries pulled in by `pip install` got updated to a version too new for the python in Debian (maybe switch to `python3` as talked about [here](https://www.raspberrypi.org/forums/viewtopic.php?t=273369)).

Since this isn't a problem in the `php:7.2-apache` image (but with extra packages installed on top), it doesn't seem like there is something for us to change in the image. In the future, it'd be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
