### ISSUE TITLE
Php 7.4.9 Catpcha Code Not Working

### ISSUE THREAD

**Issue by shahid1579** [docker-library/php#1068]
This Code works fine in php 7.2 but not in latest version..Can you please help me
```
$code = rand(1000, 9999);
            $im = imagecreatetruecolor(50, 24);
            $bg = imagecolorallocate($im, 22, 86, 165); //background color blue
            $fg = imagecolorallocate($im, 255, 255, 255); //text color white
            imagefill($im, 0, 0, $bg);
            imagestring($im, 5, 5, 5, $code, $fg);
            header("Cache-Control: no-cache, must-revalidate");
            header('Content-type: image/png');
            imagepng($im);
            imagedestroy($im);
```

**Comment by wglambert** [comment]
These repo's are for issues with how the software is containerized in a Dockerfile, without something indicating an issue with the Dockerfile or how that software is packaged - there's nothing actionable we as maintainers of that could do.

I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
I would also try giving all the commands you ran and their resultant output, along with any relevant files or logs for reproducing the issue

**Comment by shahid1579** [comment]
@wglambert  OK Thanks I will delete this.
