### ISSUE TITLE
Permission denied issue when we are using new user in php-apache

### ISSUE THREAD

**Issue by gudipudipradeep** [docker-library/php#1070]
`RUN useradd -d /home/config -m config
RUN usermod -aG sudo config
USER config

COPY index.php ./
COPY --chown=config:config startup.sh /opt/startup.sh

ENTRYPOINT ["/opt/startup.sh"]
CMD ["apache2-foreground"]`

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs

Please help how we can configure the user to run the apache application

**Comment by wglambert** [comment]
`could not bind to address 0.0.0.0:80` either adjust Apache's configuration to use a port over 1024 or include [`--sysctl net.ipv4.ip_unprivileged_port_start=0`](https://docs.docker.com/compose/compose-file/#sysctls)
https://github.com/docker-library/docs/tree/master/php#running-as-an-arbitrary-user

**Comment by wglambert** [comment]
Closing since this seems resolved

If you have further questions you could try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
