### ISSUE TITLE
PHP_MD5 enviroment variable is created/dumped but empty

### ISSUE THREAD

**Issue by mvorisek** [docker-library/php#1077]
see https://github.com/atk4/ui/runs/1326431408#step:2:131

source image: `php:7.4-alpine`

![image](https://user-images.githubusercontent.com/2228672/97573145-9999cd00-19e9-11eb-821c-45f801078270.png)

**Comment by yosifkit** [comment]
That value and others, like the SHA256, are fetched from the PHP releases API ([example for 7.4](https://www.php.net/releases/index.php?json&max=100&version=7.4)) and only the values that exist are put in the Dockerfile, but if it has a value, it is checked.

https://github.com/docker-library/php/blob/0f0ddeac8b53fa936d870f56589abcf5646b65a8/7.4/alpine3.12/cli/Dockerfile#L62-L87

The reason for optional MD5, SHA256, and detached signature (`.asc`) was that some versions only had one or maybe even none (like pre-releases). Likely, we can just drop the MD5 env from the Dockerfile since no recent release has it.
