### ISSUE TITLE
Nginx with PHP-FPM and Traefik - Blank Page

### ISSUE THREAD

**Issue by Caaruzo** [docker-library/php#1079]
Greetings, 

Today i runned into an issue and hope someone could help me please.
An while ago i set up a stack with docker-compose, including php-fpm, traefik and nginx. 
When i try to load my website it shows me a blank page with the word "error" printed on.

NGINX Log

php-fpm.log:

Before i clean installed my machine, the stack worked like charm.
I dont run an swarm, its an standalone machine.
Cause i don't know anymore nor whats the cause of it, i hope someone can help me here please.
when i create an new file like phpinfo.php and access it, that works.

docker-compose-file

Nginx conf of mydomain.de

**Comment by Caaruzo** [comment]
added nginx log

**Comment by wglambert** [comment]
This might be of some help https://stackoverflow.com/questions/24453388/nginx-reverse-proxy-causing-504-gateway-timeout/36589120#36589120

But, you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by Caaruzo** [comment]
thanks much. Unfortionally it diodn't solved my problem. I'am going to ask over into docker forums, like you said. thanks much for the hint.
