### ISSUE TITLE
Fatal error: Uncaught Error: Class "mysql" not found in /var/www/html/conn.php:6

### ISSUE THREAD

**Issue by klmylim** [docker-library/php#1099]
So my problem is,in the localhost we can find the php.ini in the xampp 
but how can I do this inside docker using ubuntu

I had done a lot of solution but I still cant figure out what is this?
![image](https://user-images.githubusercontent.com/75625027/101362746-77924500-38db-11eb-9365-a935b13fb988.png)

**Comment by wglambert** [comment]
The image doesn't load a `php.ini` by default, as what's in your Dockerfile you're loading the `php.ini-production` one https://github.com/docker-library/docs/tree/master/php#configuration

You should try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
