### ISSUE TITLE
How to reload configuration?

### ISSUE THREAD

**Issue by figure002** [docker-library/php#1107]
I have a Dockerfile file like this:

```
FROM php:7.2-apache

COPY docker/httpd.conf /etc/apache2/sites-available/mysite.conf

RUN a2dissite 000-default
RUN a2ensite mysite
```

When I modify `docker/httpd.conf` and restart the the container, I can see that the new configuration is copied and a new Docker image is created, but for some reason, the container is still running the old configuration. Even restarting the container doesn't help. I have to run `docker system prune -a` and rebuild the container for the new configuration to become effective. How can I reload the configuration without purging all Docker images?

**Comment by wglambert** [comment]
For changes to be reflected in the `httpd.conf` you'd need to rebuild the Dockerfile and redeploy the container
If you're modifying the `mysite.conf` then changes are lost on restart without it being persisted through a volume

This previous question might help https://github.com/docker-library/php/issues/897
You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
