### ISSUE TITLE
Is there an easy way to recompile php with extra ./configure options.

### ISSUE THREAD

**Issue by WillSkates** [docker-library/php#111]
Is there an easy way of adding the option to compile with the --enable-maintainer-zts option or should I create an alternative image for this?

Sorry if i'm being blind and it's already there.

**Comment by yosifkit** [comment]
Since this is not the default or upstream recommended option and would affect the users of the image, I think the easiest would be to fork the Dockerfile and build it for your needs.

**Comment by janpapenbrock** [comment]
Same question here, I want to configure with `--enable-sockets`.

`$PHP_EXTRA_CONFIGURE_ARGS` appears to be there for exactly this purpose, however I can't get it to work... how can I do it?

**Comment by md5** [comment]
@janpapenbrock `ENV` works during build too, but I suppose it depends on what you're trying to do.

In the case of the `sockets` module, I believe it can just be added in a derived image with `docker-php-ext-install`.

See this gist, which uses an example from the PHP `sockets` documentation (slightly modified to hit `www.google.com` instead of `www.example.com`): https://gist.github.com/md5/f0ca3ba1c2b0f04785fb

You can build and test it like so:

```console
$ git clone https://gist.github.com/f0ca3ba1c2b0f04785fb.git php-sockets-test
$ docker build -t php-sockets-test php-sockets-test
$ docker run --rm php-sockets-test
```

This doesn't work in the case of some modules or for special flags like `--enable-maintainer-zts`, but it does work for `--enable-sockets` and most other "normal" modules.

**Comment by janpapenbrock** [comment]
I would swear it didn't work when I tested `RUN docker-php-ext-install sockets` yesterday (with `php:5.6-apache`), but today, it works flawlessly.

So thanks for your help! And sorry for hijacking this issue...

**Comment by tianon** [comment]
FTR, we merged some official ZTS variants in https://github.com/docker-library/php/pull/171. :+1:
