### ISSUE TITLE
kdevtmpfsi virus use 99% of cpu

### ISSUE THREAD

**Issue by safaeean** [docker-library/php#1127]
hello

i use php:7.3-fpm in my project

5 minute after start container  kdevtmpfsi proccess started and use all cpu

file exist in :
/tmp/kdevtmpfsi

**Comment by JoelLinn** [comment]
How do you start the container? Is your setup similar to the one described in #1110

**Comment by JoelLinn** [comment]
```
    ports:
    - 9000:9000
```
Same cause as in #1110 . With this, you open your php fpm instance to the WWW.

**Comment by safaeean** [comment]
> ```
>     ports:
>     - 9000:9000
> ```
> 
> Same cause as in #1110 . With this, you open your php fpm instance to the WWW.

tank you
after remove this section and `docker-compose down -v && docker-compose up -d ` problem fixed

**Comment by wglambert** [comment]
There was also a lot of discussion on this malware over at https://github.com/docker-library/redis/issues/217#issuecomment-621131031

If you want more information you could look through the other issues we've had https://github.com/issues?q=is:issue+org:docker-library+kdevtmpfsi
Or you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)

Going to close since this seems resolved

**Comment by hakuno** [comment]
Is it enough? I'm unsure.

You can close the listening port (incoming). But it may have some outgoing connection (also known as  reverse connection).

ps. the @wglambert links seem good references

**Comment by tianon** [comment]
(Locking this for the same reason as in https://github.com/docker-library/redis/issues/217#issuecomment-776126290 -- if you've been hacked, you need to perform appropriate remediation on your server and deployments, and the details of that remediation is out of scope for this repository.)
