### ISSUE TITLE
False positive vulnerability reports in Dockerhub image reviews  - please add response +  ECR false positives need AWS fix. 

### ISSUE THREAD

**Issue by mikedlr** [docker-library/php#1131]
I built a docker image based on this and uploaded it to ECR with an automatic scan.  The results of the automatic scan show 366 security vulnerabilities.  Some of these appear to be valid; for example:

CVE-2020-27844 - shows a flaw in openjpeg which might be used in a PHP application and so might be important.  

In order to mitigate these vulnerabilities the image needs to be rebuild with the latest linux / apache etc.  

I'm not treating this as a confidential security vulnerability since the [firs review of the image on Dockerhub](https://hub.docker.com/_/php?tab=reviews)  currently reads:

> 
> spurgelaurels·a month ago
> Running Apache 2.4.38, a version with several critical flaws open since 2019. 
> 
> DO NOT RUN THIS IN PRODUCTION. 

Also there's no security reporting policy for this repo and it's clearly widely known so I guess the best thing is to make users aware and hope to mitigate. 

To replicate:

1) build image
2) start Amazon AWS ECR respository
3) turn on image scan on upload
4) upload image

expected result: image scan is clean
actual result: ~350 + vulnerabilities

**Comment by JoelLinn** [comment]
Wow these reports get bigger and bigger. I even wonder how they justify this tool internally because by now it must say "DO NOT RUN THIS IN PRODUCTION" for pretty much anything but a bare busybox snapshot image. Also, this isn't an issue with this image. I'm happy though you took the time to think about it and reach out to somebody. But let's dissect this popperly:

This image (variant you are talking about) is based on the official debian buster image, all software that's included in it is from the debian package repository (excluding php itself of course which is build from the upstream php source releases).
It is true that the apache buster variant of this image uses a version of apache 2.4.38 from the debian package repository. However, it has extra patches applied by the debian team. Many of these patches backport bug and security fixes from newer versions (you can check the source of the deb package [here](https://packages.debian.org/buster/apache2)). Here is the patch list file of `apache2` version `2.4.38-3+deb10u4`:

```
fhs_compliance.patch
no_LD_LIBRARY_PATH.patch
suexec-CVE-2007-1742.patch
customize_apxs.patch
build_suexec-custom.patch
reproducible_builds.diff

# This patch is applied manually
#suexec-custom.patch
spelling-errors.patch

CVE-2019-0196.patch
CVE-2019-0211.patch
CVE-2019-0215.patch
CVE-2019-0217.patch
CVE-2019-0220-1.patch
CVE-2019-0220-2.patch
CVE-2019-0220-3.patch
CVE-2019-0197.patch
CVE-2019-10092.patch
CVE-2019-10097.patch
CVE-2019-10098.patch
import-http2-module-from-2.4.46.patch
CVE-2020-11984.patch
CVE-2020-1927.patch
CVE-2020-1934.patch
```

As you can see, there are multiple CVEs addressed since 2019. This is similar with other packages from the debian repos. It seems to me AWS ECR is unable to check for distribution patches. To be honest, I'm not a fan great fan of LTS releases myself. There is always a chance some fix is forgotten or just not marked as security fix (e.g. _accidental_ fix during refactoring). However, there must be some _feature freeze_ release available for production use... I personally try to migrate to newer stable releases as fast as possible to get the most secure software.

I'm not able to comment on the other several hundred _vulnerabilities_ reported.

To be honest I don't think it is worth it to look into all the findings at this point anyways. Finding vulnerabilities in images by meta-scanning them sounds to me like trying to prove Bayes theorem wrong - The amount of false positives is just too high for it to be useful.

**Comment by mikedlr** [comment]
Thanks @JoelLinn  for finding at least one vulnerability from report which is wrong.  I will now go and hunt for a good public way to report that back to AWS support and see if I can get them to comment since such a rate of false positives make their tool useless.  

For the review I was talking about I should have linked to the [reviews on Dockerhub](https://hub.docker.com/_/php?tab=reviews) where the top, one star, review has the text I put above  - sorry, will correct.  Since that only addresses a single software package version issue - Apache - and you've clearly shown that the Apache version in the image has addressed at least some of the vulnerabilities in 2.4.38 that review is wrong.  It would be really nice if someone from the project responded to the review with an explanation based on the one you have given.

**Comment by phy25** [comment]
This has already been covered in the FAQ: https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by mikedlr** [comment]
@phy25  thanks ;  I'm going to follow up with a question on the AWS forum to see if I can get some response.  It seems that most of the problems are in the second category - false positives - but I'd like to get through to better understanding for more of these and preferably that AWS investigate fixing clair and getting that fix downstream into their system which seems based on clair.   

example findings file attached for reference:

[AWS ECR php image scan findings.json.gz](https://github.com/docker-library/php/files/6054962/AWS.ECR.php.image.scan.findings.json.gz)

**Comment by mikedlr** [comment]
IMHO this issue can now be closed

- there's a clear comment addressing this on the Docker image review page.
- the underlying seems to have got traction on on twitter - https://twitter.com/ariadneconill/status/1399554672571072513 and so Amazon appear to have decided to fix it.

Thanks to all and anyone that got involved in with this.  Actual useful progress has been made.
