### ISSUE TITLE
Add Debian 11 (bullseye)

### ISSUE THREAD

**Issue by kisfairmed** [docker-library/php#1152]
We would like to use Postgres 13. Sadly it's not available on [Debian 10 (buster)](https://packages.debian.org/buster/libpq-dev), only on [Debian 11 (bullseye)](https://packages.debian.org/bullseye/libpq-dev). Therefore it would be nice if you would add an php8-bullseye image!

**Comment by tianon** [comment]
This is a very similar request to https://github.com/docker-library/golang/issues/316, https://github.com/docker-library/golang/issues/356, https://github.com/docker-library/python/issues/450 (and others).

The short version is that Debian 11 is still "testing" and is not yet security supported (despite being in freeze and even near release).  We will support it here after it is released.

What I would suggest in order to get the PostgreSQL 13 client libraries you need would be looking at the official packages provided by PostgreSQL upstream: https://www.postgresql.org/download/linux/debian/ (which just so happen to be maintained by the maintainer of the PostgreSQL packages in Debian from the same sources, so the compatibility and comfort level will be extremely high)
