### ISSUE TITLE
problem build basic image

### ISSUE THREAD

**Issue by Ramsteven** [docker-library/php#1157]
hello, I am trying to build an image with this docker file:

FROM php:8.0.6-apache-buster

COPY src/ /var/www/html/

EXPOSE 80

but I have had this error when running this command:
```
Step 1/3 : FROM php:8.0.6-apache-buster
 ---> 97f22a92e1d1
Step 2/3 : COPY src/ /var/www/html/
COPY failed: file not found in build context or excluded by .dockerignore: stat src/: file does not exist
```
this is the content of the src folder:
`
Dockerfile  index.php`

**Comment by wglambert** [comment]
The `src/` folder you're copying needs to be in the same directory as the Dockerfile (which is the default build context). So you could move the Dockerfile back a directory `mv Dockerfile ../`

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
