### ISSUE TITLE
CVE-2021-26691 on php-apache

### ISSUE THREAD

**Issue by sanalk86** [docker-library/php#1179]
When I ran scan for php7.4-apache I am getting CVE-2021-26691  don't know if I'm missing something,  please let me know if any fix is there.

**Comment by yosifkit** [comment]
The package was available in Debian Buster as of [yesterday](https://tracker.debian.org/news/1244356/accepted-apache2-2438-3deb10u5-source-amd64-all-into-proposed-updates-stable-new-proposed-updates/).

Since our build system makes heavy use of Docker build cache, just rebuilding the all of the buster-based apache Dockerfiles won't cause any change. So we rely on periodic base image updates (as mentioned in @phy25's link). The most recent Debian was https://github.com/docker-library/official-images/pull/10402, so the usual cadence (~30 days) puts it likely in the next week or so.

**Comment by tianon** [comment]
From https://security-tracker.debian.org/tracker/CVE-2021-26691:

> In Apache HTTP Server versions 2.4.0 to 2.4.46 a specially crafted SessionHeader sent by an origin server could cause a heap overflow

My understanding of this is that it only applies when Apache is in front of another server acting as a reverse proxy?  That's a very strange way to configure the Apache that's included in the `php:apache` images which are intended to be using the `mod_php` we build and include in them instead (so I don't think this CVE is particularly critical for us to resolve early). :sweat_smile:

**Comment by sanalk86** [comment]
@yosifkit  this is working fine for me now.

**Comment by sanalk86** [comment]
closing as this has been solved, thanks all for your suggestions for a newbie..
