### ISSUE TITLE
Update Images to Debian 11

### ISSUE THREAD

**Issue by L3tum** [docker-library/php#1189]
Debian 11 was released this weekend.

There were already multiple issues opened in the past about updating to Debian 11 (due to many missing features/libraries in Buster). So far these issues were closed with the comment to wait for the actual release.

Is this something you could do now? I'm personally waiting for it as well because a lot of libraries are only available in older versions on Buster that don't support most features or even have bugs in them. 

Many thanks

**Comment by tianon** [comment]
This is definitely something we'll get around to eventually -- if someone wants to take a stab at it, be sure to search the repository for all references to `buster` so that `bullseye` can be added in all the appropriate places.  Also, as in https://github.com/docker-library/python/pull/633 and https://github.com/docker-library/ruby/pull/357, this should also remove all references to `stretch` (since we build from source, so we support a maximum of two variants per distribution).
