### ISSUE TITLE
arm64 builds missing from latest tags

### ISSUE THREAD

**Issue by GrahamCampbell** [docker-library/php#1271]

**Comment by bobvandevijver** [comment]
Yes, this is making our builds fail as well. Note that the `latest` does seem to have them, but the `8.1.4` tagged images do not (for example [8.1.4-fpm-alpine3.15](https://hub.docker.com/layers/php/library/php/8.1.4-fpm-alpine3.15/images/sha256-089ba60ce9b2b70f112f704c50831df9df797337432693f22d5297d1ce8ea0ce?context=explore))

**Comment by wglambert** [comment]
It's currently building, you can see the amd64 queue here https://doi-janky.infosiftr.net/job/multiarch/job/amd64/

https://github.com/docker-library/php#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet
![image](https://user-images.githubusercontent.com/26428991/159049792-da0931a4-4b9c-4637-99b9-ed9cda3d284b.png)

**Comment by tianon** [comment]
Indeed, we had a lot of base image updates concurrently (Debian, Alpine, Ubuntu, etc all at once) very recently for CVE-2022-0778 which have unfortunately loaded the queue pretty heavily.

I've just adjusted the queue slightly to put PHP next in line (since it's an actual version update, not just a rebuild).
