### ISSUE TITLE
Gearman module

### ISSUE THREAD

**Issue by pnx472** [docker-library/php#1286]
Hi,

Can someone help me out by writing an example how to install php-gearman module?

Thanks

**Comment by wglambert** [comment]
The docs have a section on installing pecl and core extensions https://github.com/docker-library/docs/tree/master/php#pecl-extensions

Since it's a pecl extension you just install any dependencies (it had told me it wanted `libgearman` which on Debian is `libgearman-dev`)

```console
$ docker build -t php:test - << EOF
FROM php
RUN apt update && apt install -y libgearman-dev && rm -rf /var/lib/apt/lists/*
RUN pecl install gearman && docker-php-ext-enable gearman
EOF

Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM php
 ---> 0dde119064ea
Step 2/3 : RUN apt update && apt install -y libgearman-dev && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> f5de8f0d7937
Step 3/3 : RUN pecl install gearman && docker-php-ext-enable gearman
 ---> Using cache
 ---> ace210abaf68
Successfully built ace210abaf68
Successfully tagged php:test

$ docker run --rm php:test php -m | grep -i gearman
gearman
```

In the future questions like these are better asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
