### ISSUE TITLE
Missing php-fpm.sock file on php:8.1-fpm-alpine3.16

### ISSUE THREAD

**Issue by fjugaldev** [docker-library/php#1304]
Hi guys.

I'm trying to configure my nginx vhost in order to use php-fpm.sock but i'm getting this error:
`crit] 14#14: *216 connect() to unix:/run/php-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 172.21.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "127.0.0.1"`

I tried searching the .sock file in /run and /var/run directory but without success.

I was thinking that maybe the alpine linux does not include this file? or where could be located?

There are anything i need to install to php-fpm in order to automatically create the missing php-fpm file?

Let me know what i can do please.

Thank you so much.

**Comment by wglambert** [comment]
https://github.com/docker-library/php/issues/1138#issuecomment-799572104
>You'll want to create any sockets that you'd need.
Here's some things that might help with your usecase:
https://stackoverflow.com/questions/47056062/how-to-connect-nginx-to-php-fpm-using-unix-socket-in-docker
https://medium.com/@shrikeh/setting-up-nginx-and-php-fpm-in-docker-with-unix-sockets-6fdfbdc19f91
http://www.inanzzz.com/index.php/post/q31r/using-unix-socket-for-php-fpm-and-nginx-docker-setup

If you need further help you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
