### ISSUE TITLE
critical, high and medium vulnerabilities found in 8.1-apache-bullseye 

### ISSUE THREAD

**Issue by ashishdubey07** [docker-library/php#1312]
8.1-apache-bullseye -- image showing ### total - 42, **critical - 1**, **high - 4**, **medium - 2**, low - 35. is there any plan to fix these vulnerabilities ?

**Comment by wglambert** [comment]
It'll get updated soon on its regular monthly cadence. You can also manually update the package in your image if you wanted in the meantime https://github.com/docker-library/python/issues/728#issuecomment-1132025905

Background: 
>Tags in the [official-images] library file[s] are only built through an update to that library file or as a result of its base image being updated (ie, an image `FROM debian:buster` would be rebuilt when `debian:buster` is built). 
>
>\-https://github.com/docker-library/official-images/tree/2f086314307c04e1de77f0a515f20671e60d40bb#library-definition-files

Official Images FAQ:

> Though not every CVE is removed from the images, we take CVEs seriously and try to ensure that images contain the most up-to-date packages available within a reasonable time frame
>
> \- https://github.com/docker-library/faq/tree/6138d05aabf61563606d86f98d0ccbd99f162b33#why-does-my-security-scanner-show-that-an-image-has-cves

Since our build system makes heavy use of Docker build cache, just rebuilding the all of the Dockerfiles won't cause any change. So we rely on periodic base image updates.

> We strive to publish updated images at least monthly for Debian and Ubuntu. We also rebuild earlier if there is a critical security need. Many Official Images are maintained by the community or their respective upstream projects, like Alpine and Oracle Linux, and are subject to their own maintenance schedule.
>
> \- from the same FAQ link
