### ISSUE TITLE
Admin Penal


### ISSUE THREAD

**Issue by jkhan143** [docker-library/php#1316]

**Comment by jdreesen** [comment]
Then, maybe, you should elaborate a bit further.

**Comment by wglambert** [comment]
Closing since there isn't enough information to go by

You could also try asking your question over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
