### ISSUE TITLE
php fpm stops accepting requests

### ISSUE THREAD

**Issue by slushpuppy** [docker-library/php#1323]
Hi
 I got a collection of docker containers running a variety of versions from php 7.4 to 8.1. I have encountered an intermittent problem where sometimes nginx cannot connect to the fastcgi worker with the error recv() failed (104: Connection reset by peer). The only solution is to restart the container. I am able to bash exec into the container. What debugging steps should I perform next?

**Comment by wglambert** [comment]
You might be hitting memory or other resource limits on the php container? It should have logs for any errors.
If you want `phpdbg` it's a simple derivative Dockerfile to install it in the image https://github.com/docker-library/php/issues/1260#issuecomment-1058568305

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
