### ISSUE TITLE
New php:fpm-alpine issue (update-ca-certificates)

### ISSUE THREAD

**Issue by dreherman** [docker-library/php#1351]
Good morning,

Normally I always pull the php:fpm-alpine in my working projects. Since this morning, I think with the latest update I have some issues with certificates that need to be imported into ca-certificate via update-ca-certificates. It considers the dutch KVK certificates. (https://developers.kvk.nl/support/documentation/manual-tls-certificate) somehow the certificate import fails and I am unable to connect to KVK. Running the older version: php:8.1.13-fpm-alpine3.16 works. As I am writing this I think that it might have something to do with the update to alpine3.17

Can you guys please check this out, or let me know where to put this issue.

Best regards,

Dennis Reherman

**Comment by tianon** [comment]
Yep, sounds like it's an issue with Alpine 3.17 (specifically in their `ca-certificates` package, perhaps) -- if you expand the diffs for the change we made in https://github.com/docker-library/php/pull/1348/files#diff-1c4202b2bba0cf1dd52058e512e610fc3a5d31c0ff8a2516f40737e3fbc9fc25, you can see that they were very minimal (so any bug here is unlikely to be something in the Docker image and more likely to be an intentional or accidental change or incompatibility in one of the projects we depend on/package).

I would suggest starting with a dedicated support forum, such as [the Docker Community Slack](https://dockr.ly/comm-slack), [Server Fault](https://serverfault.com/help/on-topic), [Unix & Linux](https://unix.stackexchange.com/help/on-topic), or [Stack Overflow](https://stackoverflow.com/help/on-topic) for help narrowing down exactly what's happening in your specific case.
