### ISSUE TITLE
 Php e commerce site  for admin control panel 

### ISSUE THREAD

**Issue by saravanars** [docker-library/php#1381]
Issue are Like  image file name not found when edit click redirect to edit form. Image   file name  no show but other value are show  don't why happened and also same add new for  that's aslo show error move directly upload no found  
 When check on console forbidden 404status no such file that's

**Comment by wglambert** [comment]
I'd try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

Check the `docker logs` and see if there's any specific errors that might be relevant
