### ISSUE TITLE
Vulnerability CVE-2023-38408 found until version php 8.2 related to the OpenSSH agent

### ISSUE THREAD

**Issue by xserrat** [docker-library/php#1436]
Hi,

Using the `php-8.X` and `php-7.X` images as base image I found a [vulnerability](https://security-tracker.debian.org/tracker/CVE-2023-38408) that is considered as critical related to the openssh agent.

I didn't see the vulnerability appearing in DockerHub so I wanted to share with you the issue.

A way to fix it is by upgrading the OpenSSH version into a version equal or greater than `9.3p2` as commented in the CVE.

Thanks.

**Comment by tianon** [comment]
Sorry for the delay -- this image has since been rebuilt several times and thus would've picked up any available updates to this distribution-provided package, but you might find https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves to be interesting/useful regardless.

**Comment by xserrat** [comment]
No problem, thanks for the reply!
