### ISSUE TITLE
Self Signed Cert on Apache

### ISSUE THREAD

**Issue by tomsowerby** [docker-library/php#148]
Does anybody have an example of using the php:apache image with ssl and a self signed certificate please?

I notice a few other images on github that do fresh installs of Apache on Ubuntu but I'd like to stick with official if it's possible, we're probably missing something obvious somewhere.

An example Dockerfile would be excellent if anybody has one?

Thanks.

**Comment by kbemelmans** [comment]
You most likely just want to use an SSL proxy container that connects to this container on standard http. 

A 5 second Google gave me this back, this is a good starting point probably:
https://hub.docker.com/r/cbachich/docker-ssl-proxy/

**Comment by tianon** [comment]
Indeed, I'd recommend terminating your SSL in something like NGINX instead which then proxies to either your `php:apache`-based container or at that point even `php:fpm`.

If you're absolutely set on using SSL with this image, you'll need to supply the appropriate Apache configuration to do so, and I'd recommend using a `Dockerfile` so that your process is easily repeatable.
