### ISSUE TITLE
[php:8.3-apache] HIGH Vulnerability on apache <=2.4.57

### ISSUE THREAD

**Issue by cwrx777** [docker-library/php#1484]
Hi, 

The following vulnerabilities are found on Apache 2.4.57 which is used in php:8.2-apache and php:8.3-apache. 

CVE-2023-31122,
CVE-2023-43622,
CVE-2023-45802

Please update to apache 2.4.58.

**Comment by yosifkit** [comment]
None of these are fixed in the Debian package, so there is nothing we can do to update them. The Debian Security Team has marked them as "no-dsa Minor issue", so they are unlikely to backport fixes right now. The "no-dsa" is roughly equivalent to Ubuntu/RedHat/etc marking something as "won't fix", but since Debian is a community driven project, any DD could still propose a backported fix for the package (or later bundled in a fix for a more major security issue).

- https://security-tracker.debian.org/tracker/CVE-2023-31122: `[bookworm] - apache2 <no-dsa> (Minor issue)`
- https://security-tracker.debian.org/tracker/CVE-2023-43622: `[bookworm] - apache2 <no-dsa> (Minor issue)`
- https://security-tracker.debian.org/tracker/CVE-2023-45802: `[bookworm] - apache2 <no-dsa> (Minor issue)`

**Comment by tianon** [comment]
See also https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by webaholik** [comment]
@yosifkit - This may need to be reopened at this point these 3 CVEs shouldn't continue to sit around. The Docker image for `apache:latest` also uses Debian, and they have Apache 2.4.58 included. 

Please review:

- https://hub.docker.com/layers/library/httpd/latest/images/sha256-ecf19d91df773a43b1df424b77dfe42e992129de74919ce40f764f57e1f1fe85?context=explore
- https://github.com/docker-library/httpd/blob/89aed068235d9a480f245e03edf038621ab8ed8f/2.4/Dockerfile

**Comment by tianon** [comment]
https://github.com/docker-library/php/issues/1453#issuecomment-1927702379

> We get our builds of Apache2 from Debian, and the Debian Security Team have declined to fix these ("<no-dsa> (Minor issue)" as noted above), and Docker Hub's vulnerability scanning takes this into account:
> https://hub.docker.com/layers/library/php/apache/images/sha256-ebaa9b96a98463fe81241d70b37e24b3ed885706349aaa55aa43c475704f5c22?context=explore
> (this is the current `php:apache` on `amd64` -- note these three are not listed there either)
