### ISSUE TITLE
php-fpm pm.max_children too small

### ISSUE THREAD

**Issue by netroby** [docker-library/php#162]
The current default setting too small, please increase it

```
pm.max_children = 5
```

Why not  increase it to 50? 
Yes. i know i can create my own conf to replace this. but i just want using official docker image, do not want to maintain my own php-fpm image

**Comment by blazarecki** [comment]
You can use volume to override the default configuration without having your own Dockerfile.

**Comment by tianon** [comment]
It's a pretty serious bummer that https://secure.php.net/manual/en/install.fpm.configuration.php#pm.max-chidlren doesn't give us any official recommendation on what a "sane" value should be.  I'm really hesitant to change this since our current value is based on the default provided with the PHP distribution (https://github.com/docker-library/php/blob/85447ff6a554f05b1cb893e5edf2a2cbba848332/7.0/fpm/php-fpm.conf#L1-L2), and we try to stay as close to upstream and what they officially recommend as possible.  That being said, that file was generated from PHP 5.6's defaults, so I think it's worth double-checking PHP 7.0 now and seeing if any of the defaults have been updated.

**Comment by tianon** [comment]
Heh, now I'm even more confused; thanks `php-fpm`:
```console
$ docker run -it --rm php:7-fpm sh -c "grep -vE '^;|^ *$' /usr/local/etc/php-fpm.conf.default"
[global]
include=NONE/etc/php-fpm.d/*.conf
```

**Comment by tianon** [comment]
This looks slightly better, although makes me wonder if we need to update our approach to take advantage of this new-found include default: :smile:
```console
root@54227feee4bc:/var/www/html# grep -vE '^;|^ *$' /usr/local/etc/php-fpm.d/www.conf.default 
[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
```

**Comment by ciaranmaguire** [comment]
is above code is working fine?

**Comment by tianon** [comment]
Closing since this behavior was adjusted slightly by https://github.com/docker-library/php/pull/184, and because we're using default values provided by upstream.  If they aren't appropriate for your use case, I'd recommend changing them or petitioning upstream to change the defaults (if you think your rationale is strong enough to convince them).  Thanks!
