### ISSUE TITLE
combine ENV commands

### ISSUE THREAD

**Issue by schmunk42** [docker-library/php#204]
Just a minor thing, but these ENV commands could be combined into one to save some layers:

https://github.com/docker-library/php/blob/master/5.6/Dockerfile#L24-L34

**Comment by yosifkit** [comment]
True it could, but what does it really save us?  Shouldn't the docker builder be the one to realize when two or more layers are just docker metadata and just combine them itself?

**Comment by schmunk42** [comment]
> Shouldn't the docker builder be the one to realize when two or more layers are just docker metadata and just combine them itself?

I don't think `docker build` will get this kind of automatism, but I may be wrong. 

I just thought, since this is a heavily used base image, this kind of optimization would be in its scope. It's like combining `RUN` commands, when it makes sense.

**Comment by tianon** [comment]
With the content-addressable images changes that came with Docker 1.10, this is no longer an issue.  Layers are now de-duplicated regardless of their heritage, which makes these zero-byte layers 100% no-op (and their associated metadata is embedded directly in the image manifest, so that's part of a request Docker already makes). :+1:
