### ISSUE TITLE
php-7.0.5 tags missing on docker hub

### ISSUE THREAD

**Issue by paolomainardi** [docker-library/php#216]
As you can see here https://hub.docker.com/r/library/php/tags/ 7.0.5* tags has not been built by docker hub.

**Comment by yosifkit** [comment]
Yup, it has been updated in official images: https://github.com/docker-library/official-images/pull/1590 and the server is still building them.

**Comment by paolomainardi** [comment]
thanks a lot @yosifkit , why this operatiion is taking so long ?

**Comment by tianon** [comment]
Because PHP takes quite a long time to compile from source, and we have no
less than 21 copies of it to compile. :wink:

Add to that the amount of time it takes to push them all (and other repos
that same server is responsible for pushing), and it's non-trivial.  The
changes should be up within an hour or two.

**Comment by tianon** [comment]
Images are up now! :+1:

**Comment by paolomainardi** [comment]
Thanks a lot guys!
Il 05/apr/2016 20:58, "Tianon Gravi" <notifications@github.com> ha scritto:
