### ISSUE TITLE
Alpine Linux Packages

### ISSUE THREAD

**Issue by fabiorphp** [docker-library/php#218]
Guys, you have created an image docker cool, but I have a question.

Why not use the Alpine Linux PHP7 packages instead of compiling the package in the dockerfile script?

**Comment by yosifkit** [comment]
We compile for two reasons:
 2. installing the way upstream recommends/endorses
  - upstream PHP only releases source so that is what is used
  - we do it because most packagers add opinionated bits to their releases (generally, not specifically talking about php in alpine as I have not used it)
 1. parity with the other versions (ie the debian images)

**Comment by fabiorphp** [comment]
OK! No problem!

I think you should take a look at the packages created for PHP7 and PHP5.6 that are in Alpine, so we can build a single package with the best of everything.

Please if you have a few hours left, look to the PHP7 package was made on the link below:
http://git.alpinelinux.org/cgit/aports/tree/testing/php7/APKBUILD?id=6565601b6386afe267f8c2f6809f29765b2a4cca

**Comment by urzds** [comment]
I was wondering the same. Installing the correct build-time dependencies, building the extensions, then cleaning everything and removing the build-time dependencies again is a PITA.

**Comment by yosifkit** [comment]
@fabiorphp, thanks for the link. Unfortunately, we can't get any size benefit to building it like alpine does.  They build php into about 60 different packages so that you can `apk add` just the shared libraries that you need.  They also put the source files into a `-dev` package so that it can be fetched for linking when building your own dependencies that are not one of the sub-packages that they provide.

**Comment by shouze** [comment]
@fabiorphp maybe this issue can be closed? Alpine images size has already been reduced by https://github.com/docker-library/php/pull/239 and it will be continued in https://github.com/docker-library/php/pull/245.
