### ISSUE TITLE
Apache image backed by Alpine

### ISSUE THREAD

**Issue by ThePixelDeveloper** [docker-library/php#259]
Would it be worth the effort to swap over the apache tag to start from the Alpine base image? I'm currently building an image and bundling composer and ending up around 350MB. Was curious to find out if there was a technical reason for it not happening or if it was just a lack of time.

**Comment by yosifkit** [comment]
Currently I think it is because the `apache` part is taken directly from Debian and so it has things that users are used to existing in their php/apache world, which would not necessarily be the case in an alpine version.  Also, since the Alpine variants exist mostly for size concerned users, then they would be better served with `fpm` and something like `nginx` in front of it.

**Comment by asmaloney** [comment]
I too would be interested in this.  I'm running several WordPress sites on **php:7.0-apache** and they are weighing in at about 440-460 MB.

Alternatively if anyone has any suggestions on how to reduce the size of **php:7.0-apache** that would be welcome as well.

**Comment by ihor-sviziev** [comment]
@asmaloney as alternative you could configure two containers https://hub.docker.com/_/nginx/ 1.11-alpine (19 mb) and https://hub.docker.com/_/php/ 7.0-fpm-alpine (31 MB).
 as result it would be 50 mb instead of 164mb for base image!

**Comment by asmaloney** [comment]
@ihor-sviziev That's a good idea.  My sites are (slightly) dependent on apache though and what I have right now is working (just large) so for my use-case it's probably not worth disrupting things that much.

Thanks for the suggestion!

**Comment by ihor-sviziev** [comment]
@asmaloney here is apache container with in alpine linux: https://hub.docker.com/_/httpd/. I think we can use some parts of it to prepare apache+php container.

**Comment by selim13** [comment]
Also voting for alpine based image. Currently building it myself from Alpine's packages, as apache+mod_php is slightly more convenient to use in docker environment then php-fpm. Image size results around 120 MB (41 MB compressed). Also love Alpine's busybox.

**Comment by grachevko** [comment]
+1 for alpine image.

**Comment by vlastv** [comment]
@yosifkit @ihor-sviziev you can't use php-fpm + nginx in swarm mode, without separate step of copy and deploy all statics.

I create Docker image PHP + Apache https://hub.docker.com/r/vlastv/php/tags/. You can create PR if you known as optimize https://github.com/vlastv/docker-php.

**Comment by tianon** [comment]
Given the complexity involved in duplicating Debian's Apache configuration and usage for Alpine, I don't think this is going to be solved any time soon.

The best advice I can give is to either use the Debian version (since the size difference is not _that_ dramatic, given today's normal storage and bandwidth availability), or to use FPM (which is also much more in the spirit of Alpine's minimalism).  Thanks! :heart:

**Comment by lubo** [comment]
I beg you to reconsider adding Apache Alpine variant. Many people use Alpine not because of its size (although it's a nice benefit), but because it's simple and secure. The problem with FPM images is that I'm looking for self-contained solutions and I don't wanna write custom Nginx configurations for each application I run, mainly because it's just rewriting `.htaccess` files distributed with applications. For now, I'll probably use CLI Alpine variant and install Apache myself, but having Apache Alpine variant would make my a bit easier.

**Comment by mrtimp** [comment]
I'm working on a build for Alpine (currently 3.8 but will support 3.9) with Apache with @sudomabider.  Its taking a little longer as we are working on it outside of normal working hours but I hope to be able to raise a PR shortly for the team to consider merging:

https://github.com/mrtimp/php/pull/1

**Comment by davidbarratt** [comment]
This would be needed for a single-container alpine version of [wikimedia/mediawiki-docker](https://github.com/wikimedia/mediawiki-docker).
See: https://phabricator.wikimedia.org/T241323

**Comment by szaimen** [comment]
I would also like to see this getting added :)

**Comment by msrumon** [comment]
Voting for Apache-Alpine variant. The official Apache image has an Alpine variant already, just add PHP to it and ship it. No?

**Comment by ihor-sviziev** [comment]
@msrumon what is the benefit of it?
Ngoni + php-fpm works more optimized and stable, and using a bit less resources

**Comment by msrumon** [comment]
> @msrumon what is the benefit of it?
> Ngoni + php-fpm works more optimized and stable, and using a bit less resources

I'm not sure I can use *FPM* images to deploy my applications in the production environment, unless the environment is already preconfigured with some sort of web server and all it needs is to have something where it can forward the requests to (i.e. proxy to my apps at a specified port).

Now, if I had `php:apache-alpine`, I wouldn't need to worry about any web server. I could just build the image with all the bells and whistles it needed, yet keeping the image size as lean as it could be. ☺️

Plus, we already have an Alpine variant of the Apache web server. I mean, c'mon, don't tell me it's not incompatible with PHP in any way. 🥹
