### ISSUE TITLE
PHP 7.0-FPM Current Support

### ISSUE THREAD

**Issue by generalconsensus** [docker-library/php#265]
1. It appears that memcached via pecl doesn't support php 7
2. php7 module gd requires an additional library that isn't included in the container
3. php7 module bz2 requires an additional library that isn't included in the container

**Comment by madalinignisca** [comment]
I think those are dev libraries you talk about.

In your Dockerfile, you should install them before you trigger extension installation.

I never had problems with that.

**Comment by Iazel** [comment]
Considering the philosophy of Docker, there's no way to fetch the required libs when we use the `docker-php-ext-install` command?
For installing the required libs to run magento 2.0 I had to install a good amount of extra libraries and I had to build it many times because each time there was a missing lib... Really frustrating!
I mean, this should be pretty easy considering the canned OS, shouldn't it?

**Comment by madalinignisca** [comment]
I don't believe that is a Docker Philosophy.

Personally, I just get inspired from different Dockerfiles from the Hub and build my own solutions, as somebody can't be aware of all possible problems some others might face.

I think that some others would greatly appreciate if somebody would contribute to a solution to solve something met often by a certain niche. That's why all this is open source.

**Comment by tianon** [comment]
See https://github.com/docker-library/php/issues/75#issuecomment-353673374 for a description of how I solve this exact issue in a generic way any time I need to install compiled software within Docker (which is exactly what's happening when building PHP extensions). :heart:

**Comment by tianon** [comment]
(and a rough explanation of why having `docker-php-ext-install` get all the right dependencies automatically is not necessarily infeasible, but a _massssssive_ undertaking)
