### ISSUE TITLE
Support a CGI variant?

### ISSUE THREAD

**Issue by antoligy** [docker-library/php#280]
Hey, there are already a number of distributions supported by this image, including FPM, however CGI is not one of them.  Is it worth supporting one?  (Happy to attempt a PR if so, opening this for discussion)

**Comment by tianon** [comment]
Ouch, sorry for the hyper-long tail on this one.

In my personal experience, straight CGI is a dying breed, but beyond that needs to be invoked from a separate supervisor (such as Apache), right?  How would this even work within a Docker environment?

Additionally, what about FPM is unsuitable for the use case in which you want to see CGI? (since it uses FastCGI, and is thus essentially a more elaborate/efficient way to do CGI)

**Comment by jbboehr** [comment]
Not sure about OP, but my use case was to test a PHP extension:
https://github.com/pmjones/ext-request

CGI behaves more like FPM than CLI, but the test suite for PHP extensions
is only integrated into CGI (that I could get working anyway).

We've since moved away from GitLab CI back to GitHub/Travis which includes
CGI, so it's no longer necessary for us.

**Comment by tianon** [comment]
Interesting!

In reading https://secure.php.net/manual/en/install.unix.commandline.php, it seems like our CLI images should already be set up for this -- is that not the case?  Is there an additional flag we could add to adjust that?  What would the overhead be? (ie, what's the resulting size difference?)

**Comment by jbboehr** [comment]
This was over a year ago, so my memory is a bit fuzzy, but I don't believe
they did at the time at least.

**Comment by jbboehr** [comment]
@tianon This is the relevant code from the Dockerfile: https://github.com/docker-library/php/blob/6677546d599d3980781b520f84d03ecaad291dd1/7.2/stretch/cli/Dockerfile#L132

**Comment by jbboehr** [comment]
I personally wouldn't include the CGI build in the CLI image, the vast majority of uses cases probably don't require it. The php5-cgi binary on trusty is ~9MB. The php-cgi7.0 binary on Xenial is ~4MB.

**Comment by tianon** [comment]
Ouch, good find!  I traced it back, and it goes _all_ the way: https://github.com/docker-library/php/commit/c60948d08bbc0aec96221be5c34e7f087640ed21 (the initial commit which added the very first verison of any `Dockerfile` in this repo)

I guess the interest here isn't particularly high either -- for me, the 4-9 MB doesn't really justify making our build servers churn out additional `php:cgi` variants (since each one would have to recompile PHP from source again, and we already have way too many supported combinations), so if we were going to add this I'd be inclined to add it to `php:cli`, but the interest level doesn't seem particularly high (given that this issue has been open since 2016 and only has 7 :+1: reactions and no additional comments until today :sweat_smile:).

**Comment by jbboehr** [comment]
> I guess the interest here isn't particularly high either -- for me, the 4-9 MB doesn't really justify making our build servers churn out additional php:cgi variants (since each one would have to recompile PHP from source again, and we already have way too many supported combinations),

Makes sense when you put it like that. I just checked and wow you sure do have a lot of builds now.

I kind of expected it to be here since this is the "official" PHP docker image and PHP extension tests for SAPI-related features only support CGI. That being said, I suppose someone could use one of the distro images and just install it with `apt`, etc - not sure why I didn't do it that way originally.

In any case, we've since moved back to Travis which provides it's own full builds of PHP including CGI, so we no longer require it for our needs.

**Comment by andig** [comment]
A cgi build could be a good basis for running php-pm which relies on cgi being available why not having the need for apache or another runtime environment.

**Comment by acasademont** [comment]
Exactly what @andig said!

**Comment by smaftoul** [comment]
I also want to use ppm which requires cgi.
It's a lot faster, especially with docker for mac and osxfs.
@tianon do you accept PR ? I'm fine with doing a PR, are there any direction to add a sapi to this repo ?

**Comment by smaftoul** [comment]
@antoligy @tianon should I remove the `--disable-cgi` in `Dockerfile-{alpine,debian}.template` and set it specifically in `PHP_EXTRA_CONFIGURE_ARGS` for different sapi ?

**Comment by tianon** [comment]
Can someone do a size comparison of the `-cli` variants removing this `--disable-cgi`?  I'm tentatively OK with adding CGI support to the `-cli` variants (since I think that's where it makes the most sense and don't want to add another variant just for this, but I also want to make sure the end-user impact is low).

**Comment by Werelds** [comment]
Just arrived by the same interest as above (looking to give PPM a proper go; but I don't fancy using their image in place of my own), so I decided to compile it. This is literally just the Dockerfile from the 7.2 CLI variant, minus the flag to disable CGI.

```bash
# docker images | grep php
php                                            7.2-cgi-alpine3.7   50db61fdec7e        3 minutes ago       77.5MB
php                                            7.2-fpm-alpine3.7   3c7d0b84adf0        7 days ago          78.1MB
php                                            7.2-cli-alpine3.7   f5ecac3dbfc4        7 days ago          63.3MB
```

The FPM and CLI variants I pulled from the Hub.  So14.2 MB added, for the actual binaries we have this:

```bash
/ # ls -als /usr/local/bin/php*
 14340 -rwxr-xr-x    1 root     root      14680648 May  4 20:27 /usr/local/bin/php
 14236 -rwxr-xr-x    1 root     root      14574432 May  4 20:27 /usr/local/bin/php-cgi
```

**Comment by mictadlo** [comment]
https://github.com/docker-library/php/issues/668
