### ISSUE TITLE
 missing the MySQL extension

### ISSUE THREAD

**Issue by jackluo2012** [docker-library/php#281]
Your PHP installation appears to be missing the MySQL extension which is required by WordPress.

**Comment by hairmare** [comment]
This repository contains the code to build the official php images on docker hub. If you are just after getting wordpress up and running, you might want to try out the [official wordpress images](https://hub.docker.com/r/_/wordpress/).

If you just need to add MySQL to this image you could extend it using something like the following docker file. Using an official image is much easier since it already has everything you need.

```
FROM php
RUN docker-php-ext-install mysqli
```

**Comment by jackluo2012** [comment]
@hairmare  thanks ,but i  update
 vi ../php/5.6/fpm/Dockerfile
 74                 --with-mysql=mysqlnd \
 75                 --with-mysqli=mysqlnd \
 76                 --with-pdo-mysql=mysqlnd \
