### ISSUE TITLE
php:5.6-apache and docker attach : compatible ?

### ISSUE THREAD

**Issue by dadaxr** [docker-library/php#324]
under docker for Windows

```
docker version

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```
, after executing : 

`docker run --name MyPHPContainer -d  php:5.6-apache `

everything is running fine ( according to docker logs & docker ps )

```
docker logs MyPHPContainer

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Oct 31 21:20:32.187043 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.27 configured -- resuming normal operations
[Mon Oct 31 21:20:32.187218 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

but I cannot use the command : `docker attach MyPHPContainer`. There is no error, but the command is just hanging ... Cannot do anything except CTRL+C. 

I can however execute : `docker exec -ti MyPHPContainer bash`

Any Idea why "docker attach" is not working ( i'm quite new with docker so maybe there is something I dont get ... )

**Comment by tianon** [comment]
Sorry for the delay!

When you do `docker attach`, your local terminal gets connected directly to the container as-is -- no history is provided (so the apparent "hang" is the expected behavior).  When you type Ctrl+C, it's sending that SIGINT directly to Apache itself, and should also stop your container.  See https://docs.docker.com/engine/reference/commandline/attach/ for more information.

Also, in the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks! :heart:
