### ISSUE TITLE
memcached not starting on boot

### ISSUE THREAD

**Issue by RoosterKelly** [docker-library/php#335]
I am having a devil of a time getting memcached to start on boot. I would expect it would start simply by being installed, but even using systemctl enable memcached does not work.  If I SSH into the container and start it manually it works.  Below is my docker file.

```dockerfile
FROM php:5.5.36-apache

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
    default-jdk 
RUN apt-get install -y --no-install-recommends autoconf    
RUN apt-get install -y --no-install-recommends python python-pip

RUN apt-get update && apt-get install -y libmemcached-dev \
    apt-utils re2c g++ memcached \
    zlib1g zlib1g-dbg zlib1g-dev zlibc mysql-client php5-mysql \
    && pecl install memcached \
    && docker-php-ext-enable memcached\
    && pecl install memcache \
    && docker-php-ext-enable memcache

RUN docker-php-ext-install pdo pdo_mysql

RUN apt-get install -y gettext

RUN pip install hgapi

RUN a2enmod headers \
    && a2enmod rewrite

COPY ./apache2.conf /etc/apache2/apache2.conf

RUN mkdir /var/www/content

EXPOSE 11211

RUN systemctl enable memcached
```

**Comment by yosifkit** [comment]
There is no systemd in the image/container; the only thing running in the container is the `apache` process (with its own php workers that it manages).

I would recommend running a separate [`memcached`](https://hub.docker.com/_/memcached/) container and pointing your php configuration to the memcached container via [docker network DNS](https://docs.docker.com/engine/userguide/networking/configure-dns/) with a network created by hand (`docker network create ...`) or using docker-compose and a yml file to do it automatically (`docker-compose up -d`).

**Comment by RoosterKelly** [comment]
@yosifkit I would agree with the separate container if this was a production system. I am creating an image to allow developers to run our code base on their own system in a standardized environment converting a multi-day 20 step environment configuration to four step less than one hour setup.

My quick and likely less than elegant solution was to make my own version of `apache2-foreground` and start memcached before apache is started with exec. Which should definitely NOT be done for a production system, but works for my little desktop development environment.

**Comment by tianon** [comment]
@RoosterKelly you might also be interested in something like `supervisord`, etc. to monitor multiple processes in a single container

Another tool you might want to check out is `docker-compose` -- I find it to be _extremely_ useful for automating development environment setup since it allows you to easily orchestrate multiple containers together, and the "on-boarding" for a new system/developer can be as simple as `docker-compose up -d` and then they have the full stack running, mirroring the exact configuration used in production (separate database container, separate memcached container, etc), using the exact same images as production as well. :+1:
