### ISSUE TITLE
it should enable `--enable-mbstring` during compilation

### ISSUE THREAD

**Issue by docteurklein** [docker-library/php#34]

**Comment by bocharsky-bw** [comment]
I voting :+1: for `mbstring` out-of-the-box.

**Comment by anroots** [comment]
Support `mbstring` out of the box.

```
Fatal error: Call to undefined function Illuminate\Foundation\Bootstrap\mb_internal_encoding() in /var/www/html/vendor/compiled.php on line 1809
```

**Comment by iammichiel** [comment]
No update on this? As many others, I would like to see this enabled by default.

**Comment by yosifkit** [comment]
We have to draw the line of what to include by default and currently that line is "what must be compiled into php itself versus what can be added after".  *following upstreams recommendations, of course.

**Comment by macropin** [comment]
@yosifkit With a CentOS container, if I need mbstring, I can simply go `yum -y install php-mbstring` and I've got it. If I use this official language container then I'm so out of luck without resorting to rebuilding php in the container which defeats the purpose of official language containers.

Please find a way to allow this module (and others) to be enabled. Because without it this container is not usable.

**Comment by md5** [comment]
@macropin It isn't necessary to rebuild `php` in the container. I'm pretty sure it's been established that it can be installed like this:

```Dockerfile
FROM php
RUN docker-php-ext-install mbstring
```

I don't see any comments here that contradict that and my test from November 2014 seemed to work: https://github.com/docker-library/php/issues/34#issuecomment-62387687

**Comment by macropin** [comment]
@md5 thanks. I didn't think that script was finalised. I didn't see any docs for it.

Does this mean that the container will always be shipped with php sources included?

**Comment by md5** [comment]
@macropin The docs are unfortunately being truncated on Docker Hub, but you can read them here: https://github.com/docker-library/docs/blob/master/php/README.md#how-to-install-more-php-extensions

The `docker-php-ext-*` scripts were added in November 2014 and haven't undergone much change since then.

To answer your question, yes the container will always be shipped with the PHP source code.

**Comment by mathroc** [comment]
:+1: I'd like to have mbstring installed too

with php7+ I think it could be enabled by default and with mbstring.func_overload set to 4

**Comment by TimVervers** [comment]
Voting for mbstring already installed too!
