### ISSUE TITLE
Jessie patches missing for php:5.6-apache

### ISSUE THREAD

**Issue by mgenereu** [docker-library/php#343]
There's a bunch of patches for PHP to make extensions compile on Debian Jessie. None of those patches have been applied here. It prevents compiling the mssql ext for starters.  The patches are probably needed for other php versions as well.

**Comment by bweston92** [comment]
Do you know how these patches are applied?
If so produce a PR and provide what benefits it gives / problems it solves.

**Comment by tianon** [comment]
This sounds like it's probably similar to https://github.com/docker-library/php/issues/103 and/or https://github.com/docker-library/php/issues/85.  The patches Debian applies are mostly related to how the `configure` scripts find the relevant modules they rely on, IIRC (been a little while now since I looked at them :disappointed: :cold_sweat:).

**Comment by mgenereu** [comment]
Here's the link to the folder in the Debian php repository that has all the patches that get applied.  I'm not sure when this happens in the Debian build cycle.

https://anonscm.debian.org/git/pkg-php/php5.git/tree/debian/patches

**Comment by mgenereu** [comment]
Most interesting file in the batch for this conversation:
https://anonscm.debian.org/git/pkg-php/php5.git/tree/debian/patches/0026-temporary-path-fixes-for-multiarch.patch

**Comment by mgenereu** [comment]
Did you need something else from me on this?

**Comment by tianon** [comment]
Still trying to figure out the best way to handle this generically -- it turns out those other issues aren't actually Debian-related (#85 and #103), so wouldn't be fixed by the Debian patches. :disappointed:

In the meantime, for `mssql` specifically, I've had success building it by installing `freetds-dev` and then using `docker-php-ext-configure mssql --with-libdir=lib/x86_64-linux-gnu`, ie:
```dockerfile
FROM php:5.6
RUN apt-get update && apt-get install -y freetds-dev && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-configure mssql --with-libdir=lib/x86_64-linux-gnu && docker-php-ext-install mssql
```

**Comment by tianon** [comment]
It also installs successfully on the Alpine variants without any modification (simply via installing `freetds-dev` and running `docker-php-ext-install mssql`).

**Comment by mgenereu** [comment]
Maybe just back feeding the advise for "--with-libdir" when using the Debian based one is sufficient to most use cases?  I banged my head on the parameters but make/bash are not an area of expertise for me.  Congrats and thanks on finding one that worked.

**Comment by mgenereu** [comment]
I can do a pull request with updated docs against this file: https://github.com/docker-library/docs/blob/master/php/README.md
