### ISSUE TITLE
Why is ENTRYPOINT not set?

### ISSUE THREAD

**Issue by Hipska** [docker-library/php#346]
Is there any reason why ENTRYPOINT is not set in the php-cli DockerFile?

I am new to Docker, so maybe I misunderstood the documentation, but in my opinion, you could do `docker run php -v` instead of `docker run php php -v` if ENTRYPOINT is set to php.

**Comment by yosifkit** [comment]
Yes it is on purpose. We require all official-images to have a consistent interface so that you can do `docker run -it --rm any-image bash` (or `sh`) and get a shell.  In many images we write a small script for the entrypoint that can determine whether to pass the arguments as flags or `exec` them directly;  we did not think that this type of script was necessary for the cli version of php.

**Comment by Hipska** [comment]
Indeed, a script to determine would be better than just using `php`.

Can it be (re)considered to be an extra feature of the cli version of php container? To me as a beginner in Docker, it feeled strange that after reading the docs, that such command was not possible with the php images.

**Comment by tianon** [comment]
Seems like a sane idea @Hipska; I've opened https://github.com/docker-library/php/pull/349 to get that rolling. :+1:

**Comment by Hipska** [comment]
I'm still not convinced for the php:apache image. What would be the use case for running commands to the apache2-foreground script?

**Comment by yosifkit** [comment]
To be able to pass flags to `apache2` just like you want to pass flags and files to `php` without having to specify the binary.  So any of these:

```console
$ docker run -it --rm php:apache -h
Usage: apache2 [-D name] [-d directory] [-f file]
               [-C "directive"] [-c "directive"]
               [-k start|restart|graceful|graceful-stop|stop]
               [-v] [-V] [-h] [-l] [-L] [-t] [-T] [-S] [-X]
Options:
  -D name            : define a name for use in <IfDefine name> directives
  -d directory       : specify an alternate initial ServerRoot
  -f file            : specify an alternate ServerConfigFile
  -C "directive"     : process directive before reading config files
  -c "directive"     : process directive after reading config files
  -e level           : show startup errors of level (see LogLevel)
  -E file            : log startup errors to file
  -v                 : show version number
  -V                 : show compile settings
  -h                 : list available command line options (this page)
  -l                 : list compiled in modules
  -L                 : list available configuration directives
  -t -D DUMP_VHOSTS  : show parsed vhost settings
  -t -D DUMP_RUN_CFG : show parsed run settings
  -S                 : a synonym for -t -D DUMP_VHOSTS -D DUMP_RUN_CFG
  -t -D DUMP_MODULES : show all loaded modules 
  -M                 : a synonym for -t -D DUMP_MODULES
  -t                 : run syntax check for config files
  -T                 : start without DocumentRoot(s) check
  -X                 : debug mode (only one worker, do not detach)
```

**Comment by Hipska** [comment]
Would that not be a better place to do with a apache container instead of a php container?

**Comment by yosifkit** [comment]
The `php:apache` image is really httpd (aka apache2) with php.  It made more sense to make a php image that contains httpd (since when running php you care more about the version of php than of httpd) rather than an httpd image that contains php.  This way php could be built the way upstream recommends but not be bound by what httpd upstream recommends and just use the httpd from Debian, with their customizations that users are used.

**Comment by tianon** [comment]
Indeed, and in the case of "flags to the entrypoint", conceptually, those are "flags to the default command", which in the case of the Apache variants is Apache.
