### ISSUE TITLE
Apache mpm_event

### ISSUE THREAD

**Issue by rosineygp** [docker-library/php#353]
How can I use mpm_event with php:7-apache

There is a following line on base Dockerfile

RUN a2dismod mpm_event && a2enmod mpm_prefork

There is a way to replace change it?

note: I commented this line and rebuild image... but apache not worked.

**Comment by rydente** [comment]
Right now, #392 prevents you from changing and using that, even in your own Dockerfile.  It looks like an SELinux issue, but not completely certain yet.

**Comment by rydente** [comment]
@tianon or @yosifkit, would either of you know about SELinux/Docker Security issues preventing someone from running various Apache config commands in the `apache` tags of this image? I also can't change this setting and I have seen SELinux-like file permissions on these files when switching things over (groups and user permissions read `???` instead of `rwx`).

**Comment by rydente** [comment]
@rosineygp, I mentioned in #392 that this only happens when using `overlay2` as my storage driver for Docker on a partition using JFS.  Using `devicemapper`, this shouldn't pose a problem.

**Comment by tianon** [comment]
Sorry for the delay!  I can confirm that this does indeed work on `overlay2` (and I don't have SELinux at all -- stock Debian install here):

```dockerfile
FROM php:7.2-apache
RUN a2dismod mpm_event && a2enmod mpm_prefork
```

```console
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM php:7.2-apache
 ---> c6965aaf628c
Step 2/2 : RUN a2dismod mpm_event && a2enmod mpm_prefork
 ---> Running in db4220d1497b
Module mpm_event already disabled
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Removing intermediate container db4220d1497b
 ---> a7639b932f92
Successfully built a7639b932f92
```

So, I guess the only advice I can possibly give is to either:

1. build your base elsewhere (such as in Docker's automated builds service)
1. switch storage drivers
1. switch distros

Since this isn't an issue with the image, I'm going to close.  Sorry!

**Comment by esteinborn** [comment]
Figured I'd leave a comment here that on RHEL running Kubernetes, I changed the `storage-driver` to `devicemapper` from its default of `overlay2` and the problem was immediately resolved.

I followed the instructions here: https://github.com/docker-library/php/issues/392#issuecomment-337484590
