### ISSUE TITLE
Using ARG to provide UID and GID for www-data

### ISSUE THREAD

**Issue by kuborgh-mspindelhirn** [docker-library/php#388]
Would be nice to be able to map the www-data User to have the same UID of the non root shell user that works outside of the container. 
Allows for creating a better experience for mapped volumes.

As currently www-data is fixed to use 82 I do not see this BC if we use 82 as the default

So something like
```
ARG wwwdatauid=1001
ARG wwwdatagid=1001
RUN addgroup -g $wwwdatagid -S www-data \
	&& adduser -u $wwwdatauid -D -S -G www-data www-data
```

**Comment by kuborgh-mspindelhirn** [comment]
Any feedback on this one? //cc @tianon

**Comment by tianon** [comment]
Rather than encouraging folks to rebuild this image, I'd prefer to focus on fixes we can make to ensure this is easier to control at runtime (or in an image built `FROM` this one) -- what currently breaks if one simply uses something like `docker run --user 1001:1001` ?

Just for reference, our current `www-data` user comes directly from Debian itself:
```console
$ docker run --rm debian:jessie grep www-data /etc/passwd /etc/group
/etc/passwd:www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
/etc/group:www-data:x:33:
```

**Comment by kuborgh-mspindelhirn** [comment]
Yeah. That will work for the php library. May open up a new issue in the httpd image because that doesnt work out of the box for that one as the user is set via configuration.
Thanks!
