### ISSUE TITLE
Making `docker-php-ext-enable` script flexible

### ISSUE THREAD

**Issue by adhocore** [docker-library/php#414]
A simple thing, please take a look at below snippet:

```Dockerfile
FROM php:7.1-fpm

RUN \
  PHP_EXTENSIONS="mysqli opcache pdo pdo_mysql zip"; \
  PECL_EXTENSIONS="redis xdebug-2.5.1"; \

  docker-php-source extract \
    && pecl channel-update pecl.php.net \
    && pecl install $PECL_EXTENSIONS \
    && docker-php-ext-install $PHP_EXTENSIONS \

    # the below script fails as there is extraneous version string (-2.5.1):
    && docker-php-ext-enable $PECL_EXTENSIONS \

    # had to do something like below to get it working:
    && docker-php-ext-enable `echo $PECL_EXTENSIONS | sed -e "s/[^a-z ]//g"` \
  && docker-php-source delete
```

So the question is should `docker-php-ext-enable` trim the versions by itself or not?

Thanks :)

**Comment by tianon** [comment]
Hmm, interesting problem!  My first impression would be that our scripts probably shouldn't try to be too magical (especially since it might be difficult to determine what portion of the argument constitutes a "version number" -- for example, what if we had something like `foo-bar-1.2.3-rc1`?).

Is there a specification from the PECL folks about what valid values look like for the left hand and right hand sides of that expression?  Perhaps we can find the bit of code in `pecl` itself that parses these strings to help provide clues?

If we implement something, I think it'd probably make sense to hide it behind some kind of flag (like `docker-php-ext-enable --strip-pecl-versions ...`) so that the default behavior is the same "declarative" form as we have now, but I think we need to understand the problem space a bit more before we commit to anything. :sweat_smile:

**Comment by tianon** [comment]
Giving additional thought to this matter, I'm actually inclined to simply close this as working-as-designed, especially since there are sometimes cases where the PECL module install name and the extension name don't match, so this logic would again be broken (and we don't have a sane way to make sure it stays accurate and that we can resolve PECL's extension names properly).

Sorry! :heart:
