### ISSUE TITLE
Improve Apache security

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/php#437]
Would it make sense to add this commit to the apache version here:

https://github.com/piwik/docker-piwik/pull/63/commits/202fd013a11ab060287f72ea9349b8cb9153b9f3

(related to https://github.com/piwik/docker-piwik/pull/63)

**Comment by tianon** [comment]
Sorry for the delay!

We currently use a very stock Debian configuration, so I don't think it makes sense to adjust these defaults unless we have a strong justification for doing so (and if so, that justification really ought to be passed on to the Debian package maintainers or even upstream so that they can adjust the defaults) or a recommendation to do so directly from PHP upstream which we can link to as justification (given that this is the PHP image).  Sorry!
