### ISSUE TITLE
How to enable mhash

### ISSUE THREAD

**Issue by gpsa** [docker-library/php#439]
I already enabled hash extension on php:5.6-apache image and installed libmhash-dev, but it doesn't enable mhash.
In PHP doc. page:
> As of PHP 5.3.0, the mhash extension is emulated thru the Hash extension. This makes the mhash installation directory have no effect, and requires the hash extension enabled to make the mhash support available.

But even though it doesn't enable mhash functions

**Comment by tianon** [comment]
Sorry for the delay!

It would appear that PHP includes `--enable-hash` by default, but that does _not_ include `--with-mhash` by default, and it's very difficult to get it working after-the-fact.  The closest I got was by installing `libmhash-dev`, and using `docker-php-ext-configure hash --with-mhash=/usr` followed by `docker-php-ext-install hash`, but then it doesn't get enabled because it's already enabled in the core by default (and PHP won't load it a second time).

I think we either need to bake `--with-mhash` into the image itself (which I'm not too fond of), or use `--disable-hash` so that it can be compiled and installed successfully after-the-fact instead (which is the solution I'd be more partial to, although it obviously requires testing to ensure that my proposed solution actually works).

**Comment by tianon** [comment]
Finally got around to testing this, and `--disable-hash` allowed me to successfully do `docker-php-ext-configure hash --with-mhash` followed by `docker-php-ext-install hash`. :+1:

See https://github.com/docker-library/php/pull/627. :metal:
