### ISSUE TITLE
Remove the PHP distributive from /usr/src in installations step.

### ISSUE THREAD

**Issue by baleyko** [docker-library/php#446]
13 Mb of image size will be rescued
Why don't do that?

FYI I know why it's needed, but maybe it would be better to fetch it every time when we install an extension?

**Comment by tianon** [comment]
Sorry for the delay!

This space saving is why we leave it compressed (instead of extracted, as it used to be), and in weighing the bandwidth considerations against only 13MB of additional space, we went for the latter, and I don't anticipate us changing that (especially since we'd then have to replicate all our verification functionality at runtime):

https://github.com/docker-library/php/blob/6677546d599d3980781b520f84d03ecaad291dd1/7.2/stretch/cli/Dockerfile#L82-L97

Sorry!
