### ISSUE TITLE
How to integrate php-zts 7.1 + pthreads + apache?

### ISSUE THREAD

**Issue by CesarCarrazana** [docker-library/php#474]
Hello,

php-zts 7.1 + pthreads have a error however php-zts 7.0 + pthreads it's ok

Now I want to integrate with Apache, is this possible?

Thanks

**Comment by mikk150** [comment]
you should not put zts and apache as one image and nor you cannot, because pthreads does not work with any other SAPI than CLI [see first big red box](http://php.net/manual/en/intro.pthreads.php)

which means since you cannot use it under apache anyways, just spin up two different containers, one with php7.1-zts and other with php7.1-apache2

**Comment by SmoshySmosh** [comment]
I tried this too... As it turns out, it was not a good idea. You can read about it here: #249

**Comment by tianon** [comment]
Closing, since there's now some great reference material here about why this shouldn't be done (which should be especially useful for future travelers). :+1: :heart:
