### ISSUE TITLE
Windows Server 2016 / Nano Server support planned?

### ISSUE THREAD

**Issue by kristian-b** [docker-library/php#477]
Hello,

it would be very nice, if an official PHP Docker image based on Windows Server 2016 and/or Windows Nano server would be provided. Is that planned?

Thank you.

Kristian

**Comment by tianon** [comment]
For reference, Windows releases of PHP exist on the separate https://windows.php.net/ site.

I think this is something we're interested in seeing some development effort around, but PHP on Windows is a bit complex (as can be seen by the number of available variations for every PHP version on https://windows.php.net/download/).  Do we need to provide both thread-safe and non-thread-safe variations?  What about IIS and/or Apache?

(So to be clear, I'm a bit dubious whether this is something that we can adequately support.)

**Comment by kristian-b** [comment]
Thank you for your comment. Personally I think, that most of the scenarios where I chose a Windows Server over a Linux Server includes, that I also choose IIS and not Apache. 

In my opinion the most important image for the community would be:

* Windows Server 2016 / Nano Server
* IIS
* PHP 64bit nts

**Comment by tianon** [comment]
According to https://docs.microsoft.com/en-us/iis/application-frameworks/install-and-configure-php-applications-on-iis/using-fastcgi-to-host-php-applications-on-iis, configuring IIS to point to PHP for FastCGI involves pointing it at the `php-cgi.exe` binary directly, and then I'm assuming it runs that binary and manages the connection with it?

So this will likely need to be an image that's `FROM microsoft/iis` to be useful (since IIS and PHP will likely need to run within the same container, unless there's another way to run PHP via FastCGI separately ala `php-fpm` which isn't included in the Windows releases, and connect via IP+port).  Given that `microsoft/iis` isn't part of https://github.com/docker-library/official-images, this won't be an acceptable image to create as part of this repository, but there's obviously still value in creating this as a community initiative for folks to consume outside the official images.

**Comment by tianon** [comment]
Lots of mixed feelings here with https://lwn.net/ml/php-internals/BYAPR21MB12691FC48E2DA27075609A7DCA640@BYAPR21MB1269.namprd21.prod.outlook.com/ -- on the one hand, I'm sad for the loss of the PHP community, but on the other, I'm glad we didn't ever figure out a clean way to implement this here because now we don't have anything to deprecate. :sweat_smile:
