### ISSUE TITLE
Final images contains a `/usr/src/php.tar.xz` file

### ISSUE THREAD

**Issue by fruit** [docker-library/php#488]
Why does images contains a `/usr/src/php.tar.xz` file (12Mb)?

For example `php:7.1-fpm`...

**Comment by yosifkit** [comment]
So that it doesn't have to be downloaded again (and possibly be a slightly different version) for [installing extensions](https://github.com/docker-library/docs/tree/bed131796977528f545fe7692fd800ce90dfc382/php#how-to-install-more-php-extensions).

It was previously kept in extracted form until https://github.com/docker-library/php/pull/256.

**Comment by fruit** [comment]
Ok, clear.
