### ISSUE TITLE
feature request: https

### ISSUE THREAD

**Issue by dportabella** [docker-library/php#506]
feature request: PHP with HTTPS for development.

**Comment by tianon** [comment]
You're going to need to be a lot more specific. :wink:

You can already enable HTTPS in the Apache variants via some minor additional configuration, and the FPM variants (which are really the preferred solution) don't use HTTP or HTTPS, but rather FastCGI, so you need something like NGINX or Apache in front anyhow (which is where the HTTPS termination would occur).

**Comment by tianon** [comment]
If you're referring to the built-in webserver (https://secure.php.net/manual/en/features.commandline.webserver.php), I don't believe it even supports HTTPS, since it's just a development tool and not something recommended for real application load.

**Comment by dportabella** [comment]
I need the https on localhost for testing purposes.
I just found this docker file, which has https support on localhost by default:
`$ docker run -v ${PWD}:/srv/http --name lamp -p 8080:80 -p:1443:443 -d greyltc/lamp
`

**Comment by tianon** [comment]
Something like this should do the trick:
```dockerfile
FROM php:7.1-apache

RUN apt-get update && apt-get install -y ssl-cert && rm -rf /var/lib/apt/lists/*

RUN a2ensite default-ssl \
	&& a2enmod ssl
```

Since this isn't an issue with the image that we can fix, and is instead a request for configuration help, I'm going to close it.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
