### ISSUE TITLE
Remove PHPIZE_DEPS on stretch, similarly to Alpine

### ISSUE THREAD

**Issue by amq** [docker-library/php#513]
Introducing stretch is a unique opportunity for such a change.

APT doesn't have a functionality similar to APK's `virtual`, but looks this could be enough:

```
apt-get purge --auto-remove -o APT::AutoRemove::RecommendsImportant=false $PHPIZE_DEPS
```

Certainly, `docker-php-ext-install` would need to be also modified to re-install `$PHPIZE_DEPS`.

**Comment by tianon** [comment]
One of the main hurdles to doing this is _precisely_ that APT doesn't have something like APK's `--virtual`.  With APK, when we do `apk add --virtual .xyz foo bar baz`, and then later do `apk del .xyz`, it will _only_ remove those packages which were not already installed or required by something else.  With APT, doing `apt-get purge` on packages the user installed will simply remove them, and in some cases error out completely if they're dependencies of something else, so while this would be feasible to implement in a single script (where we could, for example, track the output of `apt-mark showmanual` and/or `dpkg-query` to determine what was already installed to some extent), it's a lot less feasible across multiple scripts (as we require, given the nature of the relationship between `configure` and `install`).  Additionally, the logic to duplicate some of that `virtual` functionality is non-trivial, and likely to simply be an additional source of bug reports from our users.

As a final thought, the primary reason we were willing to do this for Alpine/APK wasn't actually because of the `--virtual` functionality (which simply came in extremely handy for actually implementing this behavior in a sane way that's not likely to break users), but was instead because APK is so much faster at installing dependencies than APT is, and one of the explicit goals of the Alpine-based images is to be as small/minimal as possible.

**Comment by tianon** [comment]
See also the discussion on https://github.com/docker-library/php/pull/438.

**Comment by tianon** [comment]
Closing this one in favor of that one, since it has more discussion.  Thanks!
