### ISSUE TITLE
openssl version

### ISSUE THREAD

**Issue by cordoval** [docker-library/php#525]
FROM php:7.1.11-fpm-alpine

is installing 1.0.2k-r0

but it should install

1.0.2m-r0

is there a reason why?

**Comment by yosifkit** [comment]
The `alpine:3.4` image was updated ~24 days ago, while the openssl package was ~18 days ago. We rely heavily on Docker build cache so that the images aren't constantly being rebuilt for no reason. Unfortunately there is nothing between the base image and the line in the Dockerfile that would tell it to discard the docker build cache. 

https://github.com/docker-library/php/blob/287a157544a8e43032ecb2879ff778d10c0d0e37/7.1/alpine3.4/fpm/Dockerfile#L7-L27

We could probably do something like we do in the [tomcat](https://github.com/docker-library/tomcat/blob/68f75ec81727e398a223ed55fe50f9a3ff78d83f/8.5/jre8/Dockerfile#L18) images and pin a specific version so that we can force a build cache bust, but with the two CVEs ([CVE-2017-3736](https://www.openssl.org/news/vulnerabilities.html#2017-3736) and [CVE-2017-3735](https://www.openssl.org/news/vulnerabilities.html#2017-3735)) fixed in `1.0.2m` being "very difficult" and "not believed likely" to exploit it does not seem worth the effort at this time.  I think we can instead wait for the next Alpine image rebuild.

**Comment by cordoval** [comment]
"i am satisfied with my care" ~ Big Hero 6
thanks

**Comment by tianon** [comment]
![](https://media0.giphy.com/media/Lb3vIJjaSIQWA/giphy.gif)
