### ISSUE TITLE
Install `apt-utils` in Debian images

### ISSUE THREAD

**Issue by mcnesium** [docker-library/php#532]
In every build the noisy warning `debconf: delaying package configuration, since apt-utils is not installed` scrolls by. [people state, it should be installed, though](https://serverfault.com/a/358950/192776), so what about adding it to the `apt-get update` commands?

**Comment by tianon** [comment]
This is a harmless warning, and the aforementioned utility (`apt-extracttemplates`) is _only_ used for interactive question-answering, which is never used during `docker build` (since our `apt-get install` is not attached to a TTY, so we simply get the default answer to all questions).

Is there anything that adding this package to our image do for us besides removing this already-harmless warning and slightly increasing the size of the overall image?

**Comment by mcnesium** [comment]
Removing harmless but noisy warnings is good imho, because it makes real warnings stick out better. I don't know if there are any more benefits beside this, it was just a suggestion. If drawbacks outbalance, nevermind this.

**Comment by tianon** [comment]
I think the drawback of installing packages we don't actually _need_ is strong enough to warrant avoiding this.  Nothing stopping you from installing this in your own images based on these to remove the warnings from your own builds, though! :heart:

Sorry!
