### ISSUE TITLE
APC doesn't install properly on 5.6

### ISSUE THREAD

**Issue by abductedMind** [docker-library/php#544]
If you run `apt-get install php-apc` you will get `Makefile:214: recipe for target 'apc_zend.lo' failed. `

How do I get APU working with this set of docker configurations for PHP 5.6? `apt-get install php-apc` runs to the end without error but this method doesn't result in a properinstall of apc cache.

Releated:
https://github.com/docker-library/php/issues/68

**Comment by yosifkit** [comment]
Installing apc from Debian apt-repos does not work (we have a fix to prevent them from installing in https://github.com/docker-library/php/pull/542) since it is compiled and created for the Debian provided php.  The php we provide in the images is as close to upstream releases as possible, so it is built from source.  If you need any extensions then you have to use the provided `docker-php-ext-*` scripts in the images and/or pecl (as noted in the Docker Hub [docs](https://github.com/docker-library/docs/tree/57a4fbdf65f459f4ef7f1eae1ebb2b7241f91f06/php#how-to-install-more-php-extensions) and #68).

```dockerfile
FROM php:5.6
# this a version noted as working for php 5.6 on #68
RUN pecl install apcu-4.0.11 && docker-php-ext-enable apcu
# php -m | grep apcu
# apcu
```
