### ISSUE TITLE
Building docker image produce php issues

### ISSUE THREAD

**Issue by bainim** [docker-library/php#550]
Hello every one,
I have an issue concerning `php:5.6-apache ,`
My OS: `ubuntu 14.04-server`
this is my `Dockerfile` looks like:

    FROM php:5.6-apache
    MAINTAINER name <name.com>
    LABEL version="1.0"
    LABEL description="Apache 2 / PHP"
    RUN apt-get update -y \
    && apt-get install -y \
        libmcrypt-dev \
        git \
        zip unzip \
        libicu-dev \
        zlib1g-dev \
        php5 \
        php5-fpm \
        php5-pear \
        php5-dev \
        php5-apc \
        php5-common \
        php5-json \
        php5-memcache \
        php5-memcached  \
        php5-xsl \
        php5-mcrypt \
        php5-mysql \
        php5-cli \
        php5-gd \
        php5-intl \
        php5-curl \
    && docker-php-ext-install -j$(nproc) pdo_mysql mysql mysqli iconv mcrypt opcache

This is the error that i have:

     E: Package 'php5' has no installation candidate
     E: Package 'php5-fpm' has no installation candidate
     E: Package 'php-pear' has no installation candidate
     E: Package 'php5-dev' has no installation candidate
     E: Package 'php-apc' has no installation candidate
     E: Package 'php5-common' has no installation candidate
     E: Package 'php5-json' has no installation candidate
     E: Package 'php5-memcache' has no installation candidate
     E: Package 'php5-memcached' has no installation candidate
     E: Package 'php5-xsl' has no installation candidate
     E: Package 'php5-mcrypt' has no installation candidate
     E: Package 'php5-mysql' has no installation candidate
     E: Package 'php5-cli' has no installation candidate
     E: Package 'php5-gd' has no installation candidate
     E: Package 'php5-intl' has no installation candidate
     E: Package 'php5-curl' has no installation candidate

Thank you

**Comment by 0aps** [comment]
Hi @bainim ,
 
  See issue #547. Seems like now you need to install the packages directly in order to get the proper version and not the one from Debian. If it was working before and now it stopped was because of the pull request mentioned in that issue.

Regards, 
Ángel

**Comment by tianon** [comment]
You always needed to install the packages directly and not from Debian.  #547 simply updated the image to block the installation of the Debian packages because they are _not_ doing what you expect when you install them in this image.

In the previous version of this image you've built (before #547), you were actually installing a _second_ version of PHP from Debian, and that was likely getting used instead of the one compiled in this image, so your image was a fair amount larger than you want it to be, and it was not working the way you thought.

You'll need to use a combination of `docker-php-ext-install` and `pecl` (as described in the image description at https://hub.docker.com/_/php/) to install these extensions if you want to continue using this image.

I'd recommend posting to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) if you need help accomplishing that task.  Thanks!

**Comment by bainim** [comment]
Hi @0aps  @tianon 
Thank you for your response, 
What i need is that the container contains all those elements , 
So refer to your response , i need to install all those php elements manuelly ?
Maybe i need more explaination about that .

This is what i add it to the Dockerfile and it's the same result:

    FROM php:5.6-apache
    MAINTAINER name <name.com>
    LABEL version="1.0"
    LABEL description="Apache 2 / PHP"
    RUN apt-get update -y \
          && apt-get install -y  software-properties-common \
          && apt-get install -y python-software-properties \
          && echo "deb http://packages.dotdeb.org wheezy-php56 all" >> /etc/apt/sources.list.d/dotdeb.list \
          && echo "deb-src http://packages.dotdeb.org wheezy-php56 all" >> /etc/apt/sources.list.d/dotdeb.list \
          && apt-get update -y \
          && apt-get install wget -y \
          && wget https://www.dotdeb.org/dotdeb.gpg \
          && apt-key add dotdeb.gpg -y \
          && apt-get update -y \
          && apt-get install -y \

**Comment by tianon** [comment]
No, what I mean is that you should be using PECL to install things like `memcached` instead of packages if you want to use this image: (https://pecl.php.net/package/memcached)

```dockerfile
RUN pecl install memcached-3.0.4
```

**Comment by bainim** [comment]
Thank you for your response, 
I saw the link, i'm talking just for installing php5.6 , i'm not talking about the extensions ,
That's my objective for Now,
Any way thank you very much

**Comment by tianon** [comment]
When you use `FROM php:5.6-xxx`, the resulting image already has PHP 5.6 installed -- there's no need to install it.  If you want to use Debian packages instead of the PHP provided by this image, then you should use `FROM debian:xxx` instead.

**Comment by bainim** [comment]
Thank you for your response ,
I applied it and i delete the php elements 
For now it running good
