### ISSUE TITLE
How to change the site directory?

### ISSUE THREAD

**Issue by dongasai** [docker-library/php#584]
How to change the site directory?
The index.php directory of my site directory is /var/www/html/public/, how to change the Settings of the site directory?

**Comment by awfulthings** [comment]
@dongasai you need to change your virtualhost's DocumentRoot in /etc/apache2/sites-enabled/ 
```
DocumentRoot /var/www/html
```

**Comment by dongasai** [comment]
Thanks

**Comment by awfulthings** [comment]
@dongasai actually I just found that proper way is to make your own `mywebsite.conf` file within your project folder containing virtual host definition including DocumentRoot you wanted.
Next step: in DockerFile copy your `mywebsite.conf` to `/etc/apache2/sites-available` (notice that destination folder is sites-available instead of sites-enabled).
Then call `a2ensite` command to enable your custom configuration.

Your Dockerfile may look like this:
```
FROM php:7.2.1-apache

COPY ./mywebsite.conf /etc/apache2/sites-available

RUN a2ensite default.conf
# you may also use: a2enmod/a2dismod, a2ensite/a2dissite and a2enconf/a2disconf

# copy your project code

EXPOSE 80
```

**Comment by jsgv** [comment]
@awfulthings Is above still the preferred way of changing the DocumentRoot?

**Comment by tianon** [comment]
There's a simpler method documented in the `php` image description.

**Comment by jsgv** [comment]
@tianon Thanks.

Here is the link for anyone else that needs it:
https://hub.docker.com/_/php/#changing-documentroot-or-other-apache-configuration

**Comment by raghavendra89** [comment]
@tianon Thanks!

You need to add these lines to your Dockerfile:

    ENV APACHE_DOCUMENT_ROOT /path/to/new/root

    RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
    RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
