### ISSUE TITLE
What is the correct way to install drivers/extensions to PHP?

### ISSUE THREAD

**Issue by PeterBocan** [docker-library/php#588]
Hello guys, I have been trying to install PGSQL and PDO drivers to php image but unsuccessfully `FastCGI sent in stderr: "PHP message: Could not connect to database: could not find driver" while reading response header from upstream,`

this is my Dockerfile, but it does not work. Not a single idea why. 

```

FROM php:7.1-fpm

#
# Install PG SQL driver.
#
RUN sed -i 's/127.0.0.1:9000/0.0.0.0:9000/g' /usr/local/etc/php-fpm.d/www.conf \
   && apt-get update && apt-get install -y libpq-dev \
   && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
   && docker-php-ext-install pdo pgsql pdo_pgsql 

```

**Comment by PeterBocan** [comment]
There was a typo in DSN.

**Comment by stevenkitter** [comment]
it is so hard to php to play with docker

**Comment by tianon** [comment]
@stevenkitter if you just want PHP, use `FROM debian:xxx` and install PHP from Debian's repos (or Ubuntu) -- if you want PHP compiled from upstream PHP's releases, that's what this image is for (which is why the usage is a little rougher around the edges than a typical Debian or RPM-based install of PHP)

In the future, these sorts of comments would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
