### ISSUE TITLE
Missing php5enmod

### ISSUE THREAD

**Issue by jsindy** [docker-library/php#591]
Between 5.6.31-apache and 5.6.32-apache, the command is missing? anyone know how to add it back? Thank you!

**Comment by tianon** [comment]
I'm not sure why it would've existed in `5.6.31-apache`, but `php5enmod` is a Debian-ism provided by the `php5-common` package in Debian Jessie -- it doesn't exist at all in Debian Stretch (likely due to the move to PHP 7), but shouldn't have ever existed in this image since it's not an upstream-provided thing (AFAIK), and we never install `php5-common` in these images.
