### ISSUE TITLE
clear_env = yes does not have any effect in pool conf | security

### ISSUE THREAD

**Issue by ItsReddi** [docker-library/php#596]
The setting clear_env does not have any effect in container
`; Clear environment in FPM workers
; Prevents arbitrary environment variables from reaching FPM worker processes
; by clearing the environment in workers before env vars specified in this
; pool configuration are added.
; Setting to "no" will make all environment variables available to PHP code
; via getenv(), $_ENV and $_SERVER.
; Default Value: yes
clear_env = yes
`

We have a running pool configuration (www.conf), php-fpm normally do not distribute the env vars to php-fpm, by default. but somehow it does.
Even with setting clearn_env = yes the variables are still distributed

Due to this issue the all system environment variables are available in php.
In the docker world, many things (like secrets) are configured via environment variables.
This leads to a security problem & performance/memory issue.

**Comment by yosifkit** [comment]
Is that just a spelling mistake in the post: `clearn_env = yes` or is that from your config file?

We did add `clear_env = no` in https://github.com/docker-library/php/pull/93 folowing the discussion in https://github.com/docker-library/php/issues/74. It is now in [`php-fpm.d/docker.conf`](https://github.com/docker-library/php/blob/be08d2067c6c6b4b9b061a0b082bf8630117a217/fpm-Dockerfile-block-2#L26), so it should be overridable.

**Comment by ItsReddi** [comment]
no just a typo.

okay, thanks for info. then we have to override docker.conf

Maybe this info should be in docs? I mean its really a security issue if you dont check your vars and only overlook config.
normally you should be able to trust your config, and this one is even a change of fpm default behavior.

**Comment by tianon** [comment]
> Due to this issue the all system environment variables are available in php.

Due to the nature of how Docker works, this isn't entirely accurate.  The only environment variables that are available from within PHP are those that are either set by the image you're building from, or set explicitly on the container you're running.  The only thing running in that container is PHP-FPM, which is the reason why this change was deemed to be acceptable -- if you're explicitly setting environment variables on your PHP-FPM container, it's likely that you wanted them to be available to the PHP code being run (because otherwise they're doing literally nothing but taking up space in RAM).

To illustrate, here's the full set available to a `php:fpm`-based container today:

```console
$ docker pull php:fpm
fpm: Pulling from library/php
Digest: sha256:b7542777e71ee485ff2c9ead73e70e27e83491714176ddf966af36b14e351989
Status: Image is up to date for php:fpm

$ docker run -i --rm php:fpm env | sort
GPG_KEYS=1729F83938DA44E27BA0F4D3DBDB397470D12172 B1B44D8F021E4E2D6021E995DC9FF8D3EE5AF27F
HOME=/root
HOSTNAME=5e93b5e459fc
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PHP_ASC_URL=https://secure.php.net/get/php-7.2.5.tar.xz.asc/from/this/mirror
PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2
PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2
PHP_EXTRA_CONFIGURE_ARGS=--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data
PHP_INI_DIR=/usr/local/etc/php
PHPIZE_DEPS=autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c
PHP_LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie
PHP_MD5=
PHP_SHA256=af70a33b3f7a51510467199b39af151333fbbe4cc21923bad9c7cf64268cddb2
PHP_URL=https://secure.php.net/get/php-7.2.5.tar.xz/from/this/mirror
PHP_VERSION=7.2.5
PWD=/var/www/html
```

(None of these are particularly sensitive -- they're all publicly available by looking at the source `Dockerfile`.  Any other environment variables provided have been provided explicitly via `environment:` in `docker-compose.yml`/`stack.yml` or via `-e`/`--env-file` on `docker run`.)

I'm going to go ahead and close this issue since there's not really anything actionable to change in the image itself here.  If there are documentation changes that need to be made, those should happen over in https://github.com/docker-library/docs.
