### ISSUE TITLE
php/5.6/alpine3.4/fpm/Dockerfile line 9 contradicts line 94

### ISSUE THREAD

**Issue by Drugoy** [docker-library/php#597]
Comment on line 9 contradicts line 94:
lines 9-11:
```
...
# persistent / runtime deps
ENV PHPIZE_DEPS \
		autoconf \
...
```
If packages listed into variable `PHPIZE_DEPS` are runtime deps, then
lines 92-95:
```
...
RUN set -xe \
	&& apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		coreutils \
...
```
mark them as .build-deps and thus those packages will get deleted later by
line 147:
```
...
	&& apk del .build-deps \
...
```

So are packages listed on lines 11-19 runtime or build dependencies?
Because of that - one needs to reinstall some of them if they install some extensions.
For example: I had to install `autoconf` (among some other deps) before doing `pecl install memcached-2.2.0`.

**Comment by tianon** [comment]
This was an intentional choice to keep the Alpine images small -- these dependencies get re-installed by the `docker-php-ext-*` scripts automatically since they both download and install very quickly on Alpine.

I think the solution here is to fix the comment for the Alpine variants to note that better.
