### ISSUE TITLE
Connection to `pecl.php.net:80' failed: Connection timed out

### ISSUE THREAD

**Issue by linkkong** [docker-library/php#606]
When I use php7.2-fpm install mongodb ext ,it appends like that
root@678701b5fe36:/var/www/html# pecl install mongodb
Could not download from "http://pecl.php.net/get/mongodb-1.4.2.tgz", cannot download "pecl/mongodb" (Connection to `pecl.php.net:80' failed: Connection timed out)
Error: cannot download "pecl/mongodb"
Download failed
install failed
And I tyr update pecl channel 
root@678701b5fe36:/var/www/html# pecl channel-update pecl.php.net
Updating channel "pecl.php.net"
Channel "pecl.php.net" is not responding over http://, failed with message: Connection to `pecl.php.net:80' failed: Connection timed out
Trying channel "pecl.php.net" over https:// instead
Channel "pecl.php.net" is up to date
I dont't know how to do ? Can anyone help me?

**Comment by yosifkit** [comment]
Works fine here; it could've been a temporary server issue or a routing issue on your connection.  Can any container reach the internet?  Can you reach pecl.php.net from the host?  You could always try rebooting your machine (or VM).

For a wider audience reach and since this is not an issue with the container image but with connectivity, it'd be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
