### ISSUE TITLE
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.

### ISSUE THREAD

**Issue by sintetico82** [docker-library/php#615]
Hi!,
When i run `composer update`, i have the following waring:

Your command-line PHP is using multiple ini files. Run `php --ini` to show them.

I try to see with   `php --ini`

Step 14/16 : RUN php --ini
 ---> Running in b31d607eec0b
Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php/conf.d
Additional .ini files parsed:      /usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini

This is actually my Dockerfile:

--------------
FROM php:7.0.28-apache

RUN apt-get update && apt-get install -y \
        git \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
     && docker-php-ext-install -j$(nproc) gd mysqli 

RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

ADD ./app /var/www/app
ADD ./bin /var/www/bin
ADD ./composer.json /var/www
ADD ./src /var/www/src
ADD ./web /var/www/web

ADD ./docker-config/entrypoint.sh /entrypoint.sh

VOLUME /var/www
WORKDIR /var/www

RUN ls /var/www/app/*
RUN php --ini
RUN composer update

ENTRYPOINT [ "/entrypoint.sh" ]

----------

I am not skilled in php, so i don't know what i should do.

**Comment by tianon** [comment]
Is the warning causing a problem?  You'll need to be a bit more specific about what you're doing, what you expect it to do, and what it's doing instead if you want folks to be able to help you.

Since this isn't really an issue with the image and is instead a request for help with usage, I'm going to close.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!

**Comment by sintetico82** [comment]
I am sorry, you are right
