### ISSUE TITLE
php:7.1-fpm-alpine downgrade libxml

### ISSUE THREAD

**Issue by lotarbo** [docker-library/php#617]
Hi. UMI.CMS needs libxml <= 2.9.4.
My dockerfile
```
FROM php:7.1-fpm-alpine

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.3/main' >> /etc/apk/repositories \
    && apk upgrade --update && apk add --no-cache \
        freetype \
        libpng \
        libjpeg-turbo\
        libxslt \
        'libxml2==2.9.4-r3' \
    && apk add --virtual .build-deps \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        libxslt-dev \
        'libxml2-dev==2.9.4-r3' \
    && docker-php-ext-configure gd \
        --with-freetype-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
    && export NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
    && docker-php-ext-install -j${NPROC} \
        mysqli \
        opcache \
        xsl \
        gd \
    && apk del .build-deps
```
but after, i check  LIBXML_DOTTED_VERSION=2.9.5
i try delete libxml2 before install php ext, but have error 

> World updated, but the following packages are not removed due to:
>   libxml2: .php-rundeps

looks like php built with new libxml2, and i cant change this.

**Comment by wglambert** [comment]
In the [Dockerfile](https://github.com/docker-library/php/blob/master/7.1/alpine3.4/fpm/Dockerfile#L95)
```bash
RUN set -xe \
	&& apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		. . .	
                libxml2-dev \
		. . .
	\
```

Since this issue seems unrelated to any errors in the image itself I'm going to prune the issue.

Given that this is more of a usability question, it would be more suited for [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
