### ISSUE TITLE
/bin/sh: nproc: not found

### ISSUE THREAD

**Issue by lkebin** [docker-library/php#638]
My Dockerfile:

```Dockerfile
FROM php:7.0.30-fpm-alpine

RUN set -ex \
    && apk upgrade --update && apk add --no-cache \
        freetype-dev \
        libjpeg-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        imagemagick-dev \
        zlib-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt pdo pcntl ldap mysqlnd tidy zip zlib soap intl \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && pecl install redis-4.0.2 \
    && pecl install xdebug-2.6.0 \
    && docker-php-ext-enable redis xdebug
```

Will get error
```
/bin/sh: nproc: not found
```

**Comment by wglambert** [comment]
You can get the coreutils package `apk add --no-cache coreutils` or get the info from `/proc/cpuinfo/` through a command such as `grep ^processor /proc/cpuinfo | wc -l` which will count the occurrences of "processor" and output the number of cores. 

Or you can pipe grep output twice and trim the field displaying the number of cores `grep "cpu cores" /proc/cpuinfo | uniq | cut -d " " -f 3`

Given that the issue is more of a usability question, it would be more suited for [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by lkebin** [comment]
@wglambert Thanks.
