### ISSUE TITLE
Error syntaxe : can't find = in "ENV".  On build for php/7.1/jessie/apache/Dockerfile

### ISSUE THREAD

**Issue by tionebDotsamapha** [docker-library/php#645]
Hi!
On the build of this Dockerfile: php/7.1/jessie/apache/Dockerfile. 
I have this error : 
Building php-apache
ERROR: Syntax error - can't find = in "ENV". Must be of the form: name=value.

docker -v
Docker version 17.12.0-ce, build c97c6d6

Have you ideas? 
Thanks

**Comment by yosifkit** [comment]
`ENV` statements in Dockerfiles do not require an `=` for a single value. Which line is failing?  What are you using to build it? `docker build` works fine here.  Is there a reason that you are building the Dockerfile rather than just pulling it from Docker Hub?

https://docs.docker.com/engine/reference/builder/#env: 
> ```dockerfile
> ENV <key> <value>
> ENV <key>=<value> ...
> ```
