### ISSUE TITLE
master build is broken

### ISSUE THREAD

**Issue by jmglsn** [docker-library/php#657]
The travis build is failing since 4 days, is somebody checking the failure?
https://travis-ci.org/docker-library/php/builds/383965749?utm_source=github_status&utm_medium=notification

The docker repository now misses the 7.1.18 version.

**Comment by tianon** [comment]
Docker Hub not having 7.1.18 doesn't have anything to do with the Travis builds -- those are simply a rough smoke test for us to ensure this repo builds properly and to make sure PRs don't break anything major.

See https://github.com/docker-library/php#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet:

> ## See a change merged here that doesn't show up on Docker Hub yet?
> 
> Check [the "library/php" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/php), especially [PRs with the "library/php" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fphp).
> 
> For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

As for the 7.1.18 update, see https://github.com/docker-library/official-images/pull/4402.

Since the failures in those builds look like the normal GPG race conditions/flakiness we see often, I'm going to close this issue (although I've hit restart on that build also).

**Comment by jmglsn** [comment]
@tianon Thanks for the update, I was not aware how the docker hub chain for this builds looks like.
