### ISSUE TITLE
php:7.0-apache  Apache How the extension opens

### ISSUE THREAD

**Issue by niyaode** [docker-library/php#678]
I'd like to open Apache's mod_rewrite.so module

**Comment by wglambert** [comment]
You want to do what with it?

If you want to enable it, it involes restarting apache so mount any files/directories you need to persist
```console
$ docker run --rm -d --name php php:apache
$ docker exec -it php bash
root@16aac7edc709:/var/www/html# a2enmod rewrite
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
root@16aac7edc709:/var/www/html# service apache2 restart
[....] Restarting Apache httpd web server: apache2Terminated
```

**Comment by yosifkit** [comment]
@wglambert is correct. `a2enmod rewrite` will get a config file in the correct spot so that Apache will load the rewrite module. `service apache2 restart` will probably not work unless you have also installed an init system in your container.

This Dockerfile will get you an image with `mod_rewrite` enabled:
```Dockerfile
FROM php:7.0-apache
RUN a2enmod rewrite
```

You could also do it at runtime, but would have to then start apache after your changes:
```console
$ docker run -d --name my-web php:7.0-apache sh -c 'a2enmod rewrite && exec docker-php-entrypoint apache2-foreground'
$ # might as well use the entrypoint in case it does any useful setup in the future
```
