### ISSUE TITLE
Make performance pitfalls more clear when using apache tag

### ISSUE THREAD

**Issue by nphmuller** [docker-library/php#681]
Currently the documentation is written in such a way that the Apache tag is a really convenient way to setup a working apache server serving php. While this is true, it might also be good to mention the performance pitfalls of using this image.

With pitfall I mean that the image uses mod_php with the prefork mpm which is according to the apache docs by far the least performant way to serve php through apache.

https://wiki.apache.org/httpd/php

**Comment by tianon** [comment]
This is a good point -- I'm kind of on the fence as to whether we should document this explicitly though.  This is a common PHP thing (`mod_php` vs FPM), so it feels like a bit much for us to document it explicitly, and maybe it would be sufficient for us to be less encouraging of folks using this tag for everything?  It definitely takes a non-trivial amount of effort to get FPM working properly, which is why we recommend Apache with `mod_php` instead.  Typically, I'd wager folks who are really performance-sensitive will either already know that `mod_php` isn't great, or will find it quickly while researching what they can do to improve performance.

Either way, improvements to https://github.com/docker-library/docs/blob/master/php/content.md would be appreciated.

Since this isn't really a concrete issue with the image (perse), but rather a request for better documentation, I'm going to close. :+1:
