### ISSUE TITLE
USE_ZEND_ALLOC=0 to mitigate SIGSEGV in zend_hash_str_find()

### ISSUE THREAD

**Issue by ghost** [docker-library/php#689]
A [known php allocator bug](https://bugs.php.net/bug.php?id=75375) causes occasional crashes of PHP unless USE_ZEND_ALLOC=0 is set in the environment. A [reproducer was provided](https://github.com/nextcloud/server/issues/10241) and will hopefully allow this rather old problem to be fixed.

In the meantime I suggest USE_ZEND_ALLOC=0 is set to mitigate the problem.

**Comment by tianon** [comment]
Does this need to be set during the image build, or only at runtime?  Is
there a good page that talks about the pros/cons?

**Comment by dachary** [comment]
@tianon I'm not familiar with the details of the zend allocator implementation and cannot usefully comment.

**Comment by tianon** [comment]
From https://secure.php.net/manual/en/internals2.memory.management.php:

> **Note:** USE_ZEND_ALLOC=0 in the environment will stop the memory manager from functioning, all allocations fall back on the default system allocators which can be useful for debugging leaks, and should only be used for this purpose.

So, I don't think it's a good idea for us to enable this unilaterally (this is a pretty strong statement from upstream).

Looking at the first comment in https://bugs.php.net/bug.php?id=75375 from laruence, I think they're probably still very interested in finding a minimal reproducer (https://github.com/nextcloud/server/issues/10241 is definitely good, but it's nowhere near minimal, and would be a bit of a pain for them to replicate with updated PHP builds while trying to actually develop a fix, which is why they want something closer to a 10-20 line script).

**Comment by tianon** [comment]
Closing in favor of upstream's bug tracking this issue: https://bugs.php.net/bug.php?id=75375
