### ISSUE TITLE
No way to get errors from php:7.2-fpm-alpine 

### ISSUE THREAD

**Issue by RoestVrijStaal** [docker-library/php#690]
Hi, 

I stole a docker building for my own purpose: https://github.com/FabianMartin/docker-php-symfony/blob/master/alpine-php/7.2-xdebug

Unfortunately I got "connection reinitialised" at each time accessing the site via the browser (e.g. 127.0.0.1:9000). It's very hard to debug because I don't get any error messages from the php-fpm docker service. 

I see php:7.2-fpm-alpine uses /proc/self/fd/2 and so do the files in the repository I linked above.

Unfortunately I don't get any errors in my console. Trying to let them output in /var/log/error.log in my container didn't work. /var/log/error.log isn't even created. 

How to fix? Any ideas are welcome.

**Comment by wglambert** [comment]
In the Dockerfile `error_log` and `access.log` are redirected to `stderr` not stdout.
https://github.com/docker-library/php/blob/b9d625cb6a5933d457f9304bc6b07122844bc777/7.2/alpine3.7/fpm/Dockerfile#L190-L200

For why this is: https://github.com/docker-library/php/issues/358#issuecomment-271033464
>php-fpm likely closes STDOUT as part of its own startup routines.

**Comment by tianon** [comment]
> Unfortunately I got "connection reinitialised" at each time accessing the site via the browser ...

When using the FPM variants, the 9000 port is _not_ exposing the HTTP protocol, but is rather exposing the FastCGI protocol, so in order to do anything useful with it, you'll need something like NGINX or Apache in front translating HTTP requests to and from FastCGI.

There are also tools like `cgi-fcgi` which can be used to interact directly, but the experience is definitely going to be very raw (since again, a FastCGI server is not a "proper" web server by itself, but rather a lower-level building block for connecting other languages _to_ a web server).

**Comment by RoestVrijStaal** [comment]
Hmmm, Since xdebug uses port 9000 by default (which i rather want not to change), I might not be interested in php-fpm (anymore).

@wglambert @tianon thanks for the help
