### ISSUE TITLE
Apache randomly assigns an IP address / incorrect virtualhost

### ISSUE THREAD

**Issue by jin78** [docker-library/php#691]
Hi

I setup my project using PHP 5.6-apache image and all I get is a blank page with 200 response in the browser.

My dockerfile :
FROM php:5.6-apache

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y vim 

RUN mkdir /my_app
WORKDIR /my_app

COPY . /my_app

COPY config/apache/000-default.conf /etc/apache2/sites-available
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]``

The docker-compose is:
```version: '3.3'
services:
container_name: my_app
  web:
    image: 'php:5.6-apache'
    build:
      context: .
    command: "bash -c 'a2enmod rewrite && apachectl -DFOREGROUND'"
    volumes:
      - .:/my_app
      - ./config/apache:/etc/apache2/sites-available
    ports:
      - '8000:80'
```

On docker compose up I have this:
Creating network "aelv2_default" with the default driver
Creating ec ... 
Creating ec ... done
Attaching to ec
my_app     | Enabling module rewrite.
my_app     | To activate the new configuration, you need to run:my_app     |   service apache2 restart
my_app     | [Fri Jul 20 09:17:12.004565 2018] [mpm_prefork:notice] [pid 17] AH00163: Apache/2.4.25 (Debian) PHP/5.6.36 configured -- resuming normal operations
my_app     | [Fri Jul 20 09:17:12.004598 2018] [core:notice] [pid 17] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

Accessing localhost:8000 returns a blank 202 response with this in the console :+1: 
[Fri Jul 20 09:19:19.932645 2018] [:error] [pid 18] [client 192.168.192.1:32836] The intl extension is needed to use intl-based filters.
ec     | 192.168.192.1 - - [20/Jul/2018:09:19:19 +0000] "GET / HTTP/1.1" 200 366 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"

Except that I think that in order to work:
- it needs to be mapped to localhost
- intl extension must be installed

apt-get install php5-intl doesn't find any package

The project uses Twig among other packages.

Please provide a clear explanantion on why this is happening. I'm a bit confused with docker.

Thanks.

**Comment by wglambert** [comment]
Your `docker-compose.yml` isn't using your built image from the `Dockerfile`. The 200 response returns nothing because there's no contents in the directory.
Your `apt-get install` fails because you need `apt-get update` to populate the package lists

If you have further questions you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability
