### ISSUE TITLE
Disabling mb-strnig

### ISSUE THREAD

**Issue by khouloudbelguith** [docker-library/php#693]
Hi,

I need to disable the mbstring extension.
I executed this line `apt-get purge php7.1-mbstring` but no success.
But I can't find the solution.

Could you please help me

**Comment by tianon** [comment]
Doing `apt-get purge php7.1-mbstring` didn't do anything because we don't install packages from Debian (they're compiled from source instead).

You can't disable `mbstring` entirely, but you can disable the functionality it provides via `php.ini`; https://www.drupal.org/project/drupal/issues/87138 has some information about that (which amounts roughly to setting `mbstring.http_input` to `pass` via `php.ini`).

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
