### ISSUE TITLE
gpgkeys: key 1A4E8B7277C42E53DBA9C7B9BCAA30EA9C0D5763 can't be retrieved

### ISSUE THREAD

**Issue by jayeshlakum** [docker-library/php#701]
Service 'magento2' failed to build: The command '/bin/sh -c set -xe;         fetchDeps='wget';     apt-get update;     apt-get install -y --no-install-recommends $fetchDeps;     rm -rf /var/lib/apt/lists/*;         mkdir -p /usr/src;     cd /usr/src;         wget -O php.tar.xz "$PHP_URL";         if [ -n "$PHP_SHA256" ]; then         echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -;     fi;     if [ -n "$PHP_MD5" ]; then         echo "$PHP_MD5 *php.tar.xz" | md5sum -c -;     fi;         if [ -n "$PHP_ASC_URL" ]; then         wget -O php.tar.xz.asc "$PHP_ASC_URL";         export GNUPGHOME="$(mktemp -d)";         for key in $GPG_KEYS; do             gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key";         done;         gpg --batch --verify php.tar.xz.asc php.tar.xz;         rm -r "$GNUPGHOME";     fi;         apt-get purge -y --auto-remove $fetchDeps' returned a non-zero code: 2
![error](https://user-images.githubusercontent.com/35368828/44086068-0dbcac8a-9fd9-11e8-9103-3f3bedd07a10.png)

**Comment by yosifkit** [comment]
That happens all the time. GPG servers are unstable (see related issues in https://github.com/docker-library/cassandra/pull/131).  We solve this for our travis builds and on the official build servers by using a man in the middle proxy (see https://github.com/docker-library/php/pull/666).

You should be able to just pull the image rather than building it; otherwise you may need to retry a couple times or add a similar proxy.
