### ISSUE TITLE
Default options not strict

### ISSUE THREAD

**Issue by fliespl** [docker-library/php#728]
Hi,
I am looking at default php.ini config provided with this image and I am curious what's the reason of enabling options by default.
short_open_tag = On (not recommended for some time in development & produciton)
enable_dl = On (not recommended - will be deprecated in the future)

Also - wouldn't it be better to provide cli / fpm subconfigs? 

I.e. This would allow setting up cli with memory_limit = -1 setting (default for cli).

Thank you for your reply.

**Comment by wglambert** [comment]
https://github.com/docker-library/php/issues/692#issuecomment-406723231
>We don't currently do _anything_ special with `php.ini` beyond what PHP's own configure/build/install process provides, so our current situation is upstream's own default. :disappointed:

**Comment by fliespl** [comment]
@wglambert thank you!

Any recommended way on creating different configs for cli & fpm while using default production.ini?

Right now I use proposed COPY method with php.ini-production

Should I 
`COPY php.ini-production to php-cli.ini`
`COPY php.ini-production to php-fpm-fcgi.ini`
and then `RUN sed `
to replace specific options for each file or maybe there is better option?

By default on debian I can edit respective php.ini file in either /etc/php/7.2/fpm/php.ini and /etc/php/7.2/cli/php.ini

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/php#configuration

The default config can be customized by copying configuration files into the `$PHP_INI_DIR/conf.d/` directory.

**Comment by fliespl** [comment]
@wglambert not really... Since both files (for cli & fpm) will be loaded.

I.e. I want to set max_memory_limit=1G for fpm, but unlimited -1 for cli.

Your approach won't work.

**Comment by tianon** [comment]
We don't specify different paths for those use cases during `./configure` (can that even be done without re-doing a full `./configure` again?), especially since it isn't recommended that we should do so by PHP upstream that I'm aware of.

As for your use case, you should be able to use something like `php -d max_memory_limit=-1 ...` in order to set it for a one-off, or use `php -c /path/to/file.ini ...` for more CLI-specific configuration.  If you need to do that often, it should be pretty easy to create a short wrapper which you could even replace `/usr/local/bin/php` with, something like `RUN mv /usr/local/bin/php /usr/local/bin/php.orig && echo '#!/bin/bash\nexec php.orig -c /path/to/ini "$@"' > /usr/local/bin/php && chmod +x /usr/local/bin/php`.

**Comment by fliespl** [comment]
Hmm, isn't this default build on debian/ubuntu?

Let's take a look at this link. https://devanswers.co/ubuntu-php-php-ini-configuration-file/

It shows you that each software (apache2/nginx/cli etc) gets it's own php.ini from subdirectory. Is it a build time option? Couldn't find it...

**Comment by tianon** [comment]
> Hmm, isn't this default build on debian/ubuntu?

Yes, Debian and Ubuntu build that way, but our image does not -- we build FPM and CLI simultaneously, and try to stick to upstream PHP's direct recommendations which do not suggest using this split configuration, hence why we do not.

If you want to use Debian or Ubuntu's PHP builds, you should be able to do so pretty easily by using `FROM debian` or `FROM ubuntu` and installing the appropriate packages.  Otherwise, one of the workarounds I recommended above should perform in the way that you desire.
