### ISSUE TITLE
Documentation: arm32v6 php refers to arm32v6/php:7.2-apache which does not exist

### ISSUE THREAD

**Issue by de-code** [docker-library/php#741]
The documentation in https://hub.docker.com/r/arm32v6/php/ suggests to use the `arm32v6/php:7.2-apache` base image. Yet no such image exists. An apache tag does however exist for the [arm32v7](https://hub.docker.com/r/arm32v7/php/) or the [main php](https://hub.docker.com/_/php/)) images.

**Comment by yosifkit** [comment]
Yeah, that is a bug in the docs since all arches are generated from the base docs. Only the alpine based images are available for `arm32v6` since Debian does not support that architecture (`-apache` images are Debian only).

I'll see if I can make the docs hide the apache section for arches that don't have it.
