### ISSUE TITLE
SSH keys generation (probably glibc)

### ISSUE THREAD

**Issue by juliangut** [docker-library/php#752]
On an image prepared to be run as Jenkins slave, that was previously working just fine, after last update about a week ago the build process is failing: https://hub.docker.com/r/juliangut/phpdev/builds/bvgnqhbrjuj7bpyw8wxizxk/

The problem is the generation of ssh keys required by jenkins to access the running container, as mentioned it was working before but now suddenly this line (https://github.com/juliangut/docker-phpdev/blob/master/dist/jenkins/7.3/Dockerfile#L50) errors with this message: `Error relocating /usr/bin/ssh-keygen: explicit_bzero: symbol not found`

There is not that much info around but apparently this has something to do with glibc and so I tried adding it from https://github.com/sgerrand/alpine-pkg-glibc but the problem persists

Has anyone faced this issue before?

As a note the same line fails for containers php:5.6-alpine, php:7.0-alpine, php:7.1-alpine, php:7.2- alpine and php:7.3-rc-alpine

**Comment by hairmare** [comment]
[This](https://github.com/gliderlabs/docker-alpine/issues/440) could be related.

Also, anything glibc is probably not the way to go since alpine is based on [musl](https://www.musl-libc.org/) anyway.

**Comment by yosifkit** [comment]
It seems like the root of your issue is using Alpine edge packages.

> Warning: "edge" is under constant development so be careful using it in production. It is possible that bugs in "edge" could cause data loss or could break your system.
>
> \- https://wiki.alpinelinux.org/wiki/Edge

Since this is not a problem with the php images I will close.  In the future, it'd be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by juliangut** [comment]
All right, I'll dig into options other than edge, thanks
