### ISSUE TITLE
Rebuild apache-php with different port

### ISSUE THREAD

**Issue by gschoenberger** [docker-library/php#771]
Hi!
As I want to use the php:7.2-apache-stretch image with OpenShift I must change the default port from 80 to something like 8080 (it is also Docker best practice to not use privileged ports).

My first intention was to use my own Dockerfile and just rebuild my own image:
```
FROM php:7.2-apache-stretch
ARG ARG_APACHE_LISTEN_PORT=8000
ENV APACHE_LISTEN_PORT=${ARG_APACHE_LISTEN_PORT}
RUN sed -s -i -e "s/80/${APACHE_LISTEN_PORT}/" /etc/apache2/ports.conf /etc/apache2/sites-available/*.conf
USER www-data
EXPOSE ${APACHE_LISTEN_PORT}
```
Basically, my Dockerfile is working, but I am afraid about the double exposed ports:
```
d9f59af22853        php:7.2-apache-stretch-customized   "docker-php-entrypoi…"   42 minutes ago      Up 42 minutes       80/tcp, 8000/tcp    friendly_tharp
```
Currently there is no option to override base image exposed ports, I have taken a look at https://github.com/moby/moby/issues/3465 where they discuss about it and also mention docker-copyedit.

**In oder to adjust the exposed port and also only expose the correct one, I have to rebuild php:7.2-apache-stretch on my own, correct?
Any documentation on how to rebuild php:7.2-apache-stretch?**

I have tried to:
- Checkout your git repo
- Adjust the Dockerfile 7.2/stretch/apache/Dockerfile directly (although I have read about the update.sh hint)
- Then call:
`docker build --build-arg ARG_APACHE_LISTEN_PORT=8000 --force-rm -t php:7.2-apache-stretch-custom-port .` 

But the following error appears:
```
+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.UsQOSnBIxx
+ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys 1729F83938DA44E27BA0F4D3DBDB397470D12172
gpg: keybox '/tmp/tmp.UsQOSnBIxx/pubring.kbx' created
gpg: keyserver receive failed: Cannot assign requested address
```
**Any chance to change the port and rebuild the image correctly?**

THX, all the best, Georg

**Comment by gschoenberger** [comment]
Meanwhile, I gave a chance, juts for documentation:
`./docker-copyedit.py FROM php:7.2-apache-stretch INTO php:7.2-apache-stretch-no-port REMOVE PORT 80`
Then I rebuilt my image and run a test container:
```
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS               NAMES
42ccfb774ae4        php:7.2-apache-stretch-customized   "docker-php-entrypoi…"   3 seconds ago       Up 1 second         8000/tcp            awesome_lichterman
```
Running a diff on docker inspect it only removed:
```
            "ExposedPorts": {
                "80/tcp": {}
            },
```
At least I have a work around...

**Comment by wglambert** [comment]
The port you're seeing in `docker ps` is the [exposed](https://docs.docker.com/engine/reference/builder/#expose) port in the Dockerfile
https://github.com/docker-library/php/blob/0e5c984e02d9027c25794bfb5002a2f9da26a7ec/7.3/stretch/apache/Dockerfile#L280

This is only available to other containers on the same docker-network. For doing container to host communication you'll want [`--publish`](https://docs.docker.com/engine/reference/run/#expose-incoming-ports) which will allow container connections with the host and anything connected to the host on the published port

**Comment by gschoenberger** [comment]
Yes, I know that the ports in `docker ps` are the exposed ones.
Want I want to achieve:
- Use php:7.2-apache-stretch as base image
- Override the default exposed port 80 with 8000
- Ensure that only the port 8000 is the exposed one (in order to not "confuse" other containers in OpenShift)
 -> this is currently not possible without rebuilding the base image or use tools like docker-copyedit.

**Comment by yosifkit** [comment]
> Override the default exposed port 80 with 8000

This is just image metadata that happens to bleed into container metadata and a user's apache configuration could easily be using different ports.

> Ensure that only the port 8000 is the exposed one (in order to not "confuse" other containers in OpenShift)

That really sounds like a openshift problem; the Dockerfile for the image only defines the default port that the image could use, not the ones that will actually be used.  While convenient if one controls all layers of their images, the orchestration system shouldn't be using `EXPOSE` metadata for its service discovery.

--------

On a related topic, "privileged ports" is an archaic notion with respect to containers since they each have their own network namespace. To get around the limitation of only root being able to use them, you can just add `--sysctl net.ipv4.ip_unprivileged_port_start=0` and run as any user desired (https://github.com/docker-library/httpd/issues/102#issuecomment-403957642).

**Comment by wglambert** [comment]
Since there isn't anything denoting an error with the image I'm going to close.

If you have other questions you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability
