### ISSUE TITLE
PHP-FPM Always returns 200 response code regardless PHP errors

### ISSUE THREAD

**Issue by mahnunchik** [docker-library/php#779]
PHP-FPM Always returns 200 response code regardless PHP errors.

I've reproduced this behaviour with any php:*-fpm-* image from Docker hub without any modification in php config.

Original: https://stackoverflow.com/questions/54290280/php-fpm-always-returns-200-response-code-regardless-php-errors

**Comment by tianon** [comment]
It looks like your Stack Overflow post hasn't been open long enough to give anyone a chance to answer. :wink:

We don't do anything special in our packaging of PHP-FPM, so this is very likely either a bug in configuration, environment, or usage.  I'd say help from folks on Stack Overflow is probably your best bet in tracking this down.  If it turns out to be something we reasonably _could_ fix by default here in the image (preferably backed up by explicit documentation/recommendation from PHP upstream), then that's something worth considering.

**Comment by mahnunchik** [comment]
@tianon I've added test repo to reproduce behaviour https://github.com/mahnunchik/php-fpm-response-code

**Comment by olvlvl** [comment]
You can easily fix this with:

```php
http_response_code(500);
```

**Comment by yosifkit** [comment]
It looks like this is PHP working as intended. Closing.
