### ISSUE TITLE
php:7.2.6-apache lost php.ini-* config

### ISSUE THREAD

**Issue by grayside** [docker-library/php#803]
The `php.ini-development` and `php.ini-production` files are present in tag php:7.2-apache, but are missing in tag php:7.2.6-apache. Confirmed with pulls to both tags today.

**Comment by tianon** [comment]
The latest 7.2 release is 7.2.**16** -- was this a typo, or are you really trying to use that ancient release version? (Released: 24 May 2018, from https://secure.php.net/releases/#7.2.6)

To be clear, 7.2.6 is long-since no longer supported or maintained, so it doesn't surprise me to learn that it's missing things (it was likely pushed long before we merged https://github.com/docker-library/php/pull/711, which appears to have been added around 7.2.9).

**Comment by grayside** [comment]
Fair enough to call it unsupported, but it did have those files previously. I am filing this more to question: where did it go? I did not audit to see if it was missing in more recent versions or other variants.

**Comment by tianon** [comment]
I'm saying it's really not possible for `php:7.2.6` tags to have included those files previously because we didn't add them until 7.2.9 and we only support the very latest release (matching PHP upstream).

**Comment by grayside** [comment]
Alright. In which case I have no idea what happened :)

Thanks for the impressively quick response!

**Comment by tianon** [comment]
You should be able to get what the contents of those files would have been at 7.2.6 from https://github.com/php/php-src/blob/php-7.2.6/php.ini-development and https://github.com/php/php-src/blob/php-7.2.6/php.ini-production.

Since there isn't really anything for us to fix here, I'm going to close. :+1:
