### ISSUE TITLE
Nightly builds of unreleased PHP versions

### ISSUE THREAD

**Issue by martinssipenko** [docker-library/php#825]
Hi,

Are there any plans to build nightly snapshot builds of unreleased PHP versions such as 7.4 and 8.0? This would greatly help framework/library/application authors to test their projects against upcoming PHP versions.

**Comment by wglambert** [comment]
https://github.com/docker-library/julia/issues/25#issuecomment-434867037

Similar issues: https://github.com/docker-library/official-images/issues/1281, https://github.com/rust-lang-nursery/docker-rust/issues/5, https://github.com/docker-library/docker/issues/125

> Any `nightly` or `dev` image in the official images would still need to maintain the repeatability aspect.  All builds make heavy use of docker build cache so if the `RUN` line does not change, the image would not change.  Base images get updates and cause dependent images to rebuild and we don't want those situations to cause a version bump to the main software of the image.  The only other time an image gets built is via a commit in official-images that changes the respective `library/` file.  `eggdrop` is one image that has a `develop` build that they update once in a while (like https://github.com/docker-library/official-images/pull/3051).

Nightly builds aren't something we can feasibly maintain

**Comment by GrahamCampbell** [comment]
Getting PHP 7.4 releases once the PHP core team start doing alpha tags would be great. That way it's not "nightly".

**Comment by martinssipenko** [comment]
Fair enough, having having pre-stable releases (alpha, beta, RC) makes more sense. @wglambert do you think this could be achievable?

**Comment by GrahamCampbell** [comment]
I'd expect PHP 7.4.0alpha1 to be released either in June or July this year, and then alpha releases to occur every 2 weeks until beta starts, and then beta releases every 2 weeks until RC, just like 7.3 last year. As far as I'm aware, the tentative 7.4.0 stable release date is December this year.

**Comment by tianon** [comment]
That's definitely something we're hip about, and have provided in the past (see also https://github.com/docker-library/php/blob/e63194a0006848edb13b7eff5a7f9d790d679428/update.sh#L55-L82 for where in `update.sh` we still have logic for scraping pre-releases).

Once PHP 7.4.0alpha1 drops, we'll be looking to include it. :+1:

I'm going to close this though since there's nothing actionable right now given that we really can't do proper nightly builds effectively.  That being said, it shouldn't be too hard for someone to take our `Dockerfile` and create an image that mirrors ours but builds directly from a specific commit from upstream and publish/maintain it under a separate organization for users to consume. :+1:

**Comment by GrahamCampbell** [comment]
PHP 7.4.0alpha1 has now been released. :)

**Comment by tianon** [comment]
I see a tag at https://github.com/php/php-src/blob/php-7.4.0alpha1/NEWS, but no release artifacts at https://qa.php.net/ yet :confused:

**Comment by tianon** [comment]
Aha, it needs an update to https://github.com/php/web-qa/blob/master/include/release-qa.php before it shows up in the API where we can scrape it properly.

**Comment by GrahamCampbell** [comment]
Oh, I see. It'll be appearing there tomorrow I think, in line with the release date. :)

**Comment by tianon** [comment]
https://github.com/docker-library/php/pull/840 :+1:
