### ISSUE TITLE
i build php by Dockerfile and failed

### ISSUE THREAD

**Issue by qzd1989** [docker-library/php#858]
i didn't change anything, download and use to build from php/7.3/stretch/fpm

`The command '/bin/sh -c set -eux; 		savedAptMark="$(apt-mark showmanual)"; 	apt-get update; 	apt-get install -y --no-install-recommends gnupg dirmngr; 	rm -rf /var/lib/apt/lists/*; 		mkdir -p /usr/src; 	cd /usr/src; 		curl -fsSL -o php.tar.xz "$PHP_URL"; 		if [ -n "$PHP_SHA256" ]; then 		echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -; 	fi; 	if [ -n "$PHP_MD5" ]; then 		echo "$PHP_MD5 *php.tar.xz" | md5sum -c -; 	fi; 		if [ -n "$PHP_ASC_URL" ]; then 		curl -fsSL -o php.tar.xz.asc "$PHP_ASC_URL"; 		export GNUPGHOME="$(mktemp -d)"; 		for key in $GPG_KEYS; do 			gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; 		done; 		gpg --batch --verify php.tar.xz.asc php.tar.xz; 		gpgconf --kill all; 		rm -rf "$GNUPGHOME"; 	fi; 		apt-mark auto '.*' > /dev/null; 	apt-mark manual $savedAptMark > /dev/null; 	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false' returned a non-zero code: 2`

**Comment by qzd1989** [comment]
i give up , use vagrant~

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749

If you try it a few more times it should work. Is there a particular reason you're building the image instead of doing a `FROM php:7.3-fpm`
