### ISSUE TITLE
LogFormat Directive not honored

### ISSUE THREAD

**Issue by patricklee2** [docker-library/php#863]
using 7.3-apache
tried to change the format of the log

in apache2.conf
Added 

```
LogFormat "%t %h \"%r\" %>s %b  \"%{Referer}i\" \"%{User-agent}i\" \"%{Disguised-Host}i\"" tuxedoformat'
CustomLog /dev/stderr tuxedoformat
```

but format was not honored

**Comment by wglambert** [comment]
You want `/proc/1/fd/2` instead of `/dev/stderr`

https://github.com/docker-library/php/issues/811#issuecomment-481029692
tl;dr: using `/dev/stderr` redirects to `/proc/self/fd/2` which redirects to `/dev/pts/0`
And `docker logs` reads from `/proc/1/fd/{1,2}` (when the container is `-d` or "detached")

**Comment by allofmex** [comment]
Can't explain why, but it seems to be important to use an **own name** instead of existing ones (at least in virtual host file).

This
```
<VirtualHost *:80>
    LogFormat "%v:%p ..." vhost_combined
    CustomLog /proc/self/fd/1 vhost_combined
</VirtualHost>
```
get's ignored, but

```
    LogFormat "%v:%p ..." vhost_combined_new
    CustomLog /proc/self/fd/1 vhost_combined_new
```
works.
