### ISSUE TITLE
file_get_contents on localhost : Connection refused

### ISSUE THREAD

**Issue by Gu3** [docker-library/php#872]
Hi ! 
I've got a problem to access to my local files from a container.
I've got one nginx container and one php fpm container. 
I can access to my php fpm container with the url local.api.fr:8080
but inside the php fpm container, if I do : 
file_get_contents('local.api.fr:8080'), I've got a "failed to open stream: Connection refused."
 This is a part of my docker-compose file : 

![image](https://user-images.githubusercontent.com/5227741/62142737-263d7300-b2ef-11e9-8ecf-7dcf4a9a993f.png)

Thanks you for your help 
Cheers 
Vincent.

**Comment by wglambert** [comment]
Your php container isn't in the host network namespace, so it accesses containers through their hostname/address.

That `8080:80` binding is for host->container. So for inter-container communication you'll use port `80` for connecting. And your `local.api.fr` probably has to be added to the container's `/etc/hosts` file

If you have further questions you could also try asking the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability
