### ISSUE TITLE
7.2.20+ fail with Package 'mysql-client' has no installation candidate

### ISSUE THREAD

**Issue by whomobile** [docker-library/php#903]
after version 7.2.20, `apt-get install -y mysql-client` is failing.

It looks stretch -> buster change following commit cause that. 
afa08b1838294089a465f97f87ea7a960039fda0 

`Package mysql-client is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mysql-client' has no installation candidate`

**Comment by wglambert** [comment]
[`default-mysql-client`](https://packages.debian.org/buster/default-mysql-client) looks like its replacement in Buster

There is still a `stretch` variant if Buster isn't suitable
https://packages.debian.org/search?searchon=names&keywords=mysql-client

Going to close since this isn't an issue with the image

**Comment by JoelLinn** [comment]
I don’t know why you need that in a php container but anyways:

Debian buster packages mariadb as default. Either switch to `mariadb-client` or use a php image tag thats based on debian stretch, e.g. `php:7.3-apache-stretch`

This is not aN inherent problem of this image.

**Comment by whomobile** [comment]
Certainly agree with you. Thank you. anyway because my existing dockerfile
use php as base image and after upgrade it stop works, so I want to find
solution. And I found it. Thank you
