### ISSUE TITLE
curl extension fails to install on php:7.3.12-fpm-stretch

### ISSUE THREAD

**Issue by jelovac** [docker-library/php#922]
Hi,

I wanted to upgrade the base image from **php:7.3.9-fpm-stretch** to **php:7.3.12-fpm-stretch** however the docker build fails with the following error message:

> Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
configure: error: unrecognized options: --with-openssl

The Dockerfile example:

```
FROM php:7.3.12-fpm-stretch

# Install necessary packages
RUN \
	apt-get update \
	&& apt-get install -y \
		build-essential \
		cron \
		git \
		locales \
		openssl \
		pkg-config \
		unzip

# Install PHP extensions which depend on external libraries
RUN \
    apt-get update \
    && echo 'Installing PHP curl extension' \
    && apt-get install -y --no-install-recommends libssl-dev libcurl4-openssl-dev \
    && docker-php-ext-configure curl --with-curl --with-openssl=/usr \
    && docker-php-ext-install -j$(nproc) curl
```

Remarks:

- changed only the FROM part, everything else in the Dockerfile is the same between the new and old version
- tested the build again with old version, builds successfully without issues
- tried to replace --with-openssl flag to --with-openssl-dir =>same error type

**Comment by JoelLinn** [comment]
First of all:
> configure: error: unrecognized options: --with-openssl
says it all. That option just needs to be omitted.

Then, isn't curl included by default? At least on buster cli it is. That would render all of your Dockerfile obsolete.

**Comment by yosifkit** [comment]
Yeah the images have been building php `--with-curl` since 2014 (#27).

The `configure: error: unrecognized options` you are getting was a result of #918. (sorry for breaking that, but we thought it was important especially with the changes in 7.4 like mentioned [here](https://github.com/docker-library/php/pull/910#issuecomment-559383597))

**Comment by jelovac** [comment]
Thank you guys for clarifying this.

Do you have a list of php-extensions which come witch the images by default or do we need to check from the running container?

**Comment by yosifkit** [comment]
No concrete list, since it can change from version to version (php upstream changes or changes here). We do try to minimize our changes and only include modules that are required or difficult/impossible to use as an external module.

So yes, you need to check that the version you are using  has the module included (https://github.com/docker-library/docs/pull/1567):

> ### Default extensions
>
> Some extensions are compiled by default. This depends on the PHP version you are using. Run `php -m` in the container to get a list for your specific version.

Maybe something like a `php -m | grep 'full-module-name'` in a Dockerfile `RUN` line should make sure that the module you expect is there when building your image.

**Comment by jelovac** [comment]
Ok, thanks for additional info.

I will close the issue.

Best regards,
Vladimir
