### ISSUE TITLE
How do I connect

### ISSUE THREAD

**Issue by kyle4229** [docker-library/php#942]
How do I connect

_Originally posted by @kyle4229 in https://github.com/docker-library/php/issues/941#issuecomment-573402182_

**Comment by wglambert** [comment]
I don't know what issues you're having but they'd be appropriately filed over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos are for issues with the Dockerfiles we maintain and not a user-help forum
