### ISSUE TITLE
"Too many levels of symbolic links" when trying to create containers.

### ISSUE THREAD

**Issue by STaRDoGG** [docker-library/php#944]
I'm running into a problem, and I can't get some containers up.

(_I was referred here from this thread, so all the details so far are there, rather than re-typing it all_):

https://github.com/phpmyadmin/docker/issues/267

**Comment by wglambert** [comment]
In your case ghis is probably related to Docker for Windows using linux containers

**Comment by STaRDoGG** [comment]
@wglambert Thanks for taking the time to look into this for me, I appreciate it.

I will go through all of the links you referenced later tonight when I get back home, but just a couple of things I thought I might mention;

I have 49 containers currently running all the time, 3 of them are on that list. MySQL, Jenkins nad WordPress, all seem to run fine. I also run an Adminer container, but I've been using PHPMyAdmin for so many years I'm used to it, and would prefer to use that over Adminer. So that's kind of confusing.

Also, maybe I'm misunderstanding, I'm still relatively new to Docker and learning my way around, but when it talks about bind mounts not working, is it referring to internal mounds before I even add my own via `-v` etc.? Because I get the error even w/out adding my own mounts/volumes.

Last question:
When it refers to LCOW, is it meaning the 'old' style where it runs the Linux containers in a Hyper-V VM? Or the 'new' style with WSL? I'm assuming the former, but just want to be sure.

**Comment by wglambert** [comment]
Bind mounts are mounting a file/folder from the host to the container. A [named volume](https://success.docker.com/article/different-types-of-volumes) will work fine for Linux containers on Widows 

[WSL2](https://docs.docker.com/docker-for-windows/wsl-tech-preview/) (the new tech preview) still uses hyper-v https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq I'm not sure of the underlying filesystem and if the bind-mount issues are alleviated 

You'd probably get a lot more knowledgeable input asking over at https://github.com/docker/for-win, there isn't really anything we could change in the image for this since it's host/environment related
