### ISSUE TITLE
COPY failed: stat /var/lib/docker/tmp/docker-builder123280183/docker-entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by nags28** [docker-library/php#947]
FROM python:3.6
COPY docker-entrypoint.sh /

RUN    yum --no-cache add --virtual=.build-dep build-base \
    && yum --no-cache add libzmq \
    && pip install --no-cache-dir locustio==0.8.1 \
    && yum del .build-dep \
    && chmod +x /docker-entrypoint.sh

RUN  mkdir /locust
WORKDIR /locust
EXPOSE 8089 5557 5558

ENTRYPOINT ["/docker-entrypoint.sh"]

The above content is my docker file where i'm unable to copy shell file its getting failed can someone please help me

**Comment by wglambert** [comment]
Are you using Docker for Mac/Win?

Is that file in the same directory as the Dockerfile

**Comment by nags28** [comment]
Ec2 Amazon Linux machine

**Comment by wglambert** [comment]
Since this isn't an image related issue but one with either Docker or the host environment I would recommend asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
