### ISSUE TITLE
Apache2 foreground does not source /etc/apache2/envvars

### ISSUE THREAD

**Issue by leftyhitchens** [docker-library/php#97]
The envvars file is not sourced int eh apache2-foreground script so environment variables like APACHE_LOGS_DIR are not resolved, is this intentional? What is the best way to handle things like logging?

**Comment by thaJeztah** [comment]
The Apache servers log to STDOUT, this makes Docker pick-up the logging so that logging can be handled outside of the container, using the logging options that Docker offers. See these lines in the Dockerfile;

```
	&& sed -ri ' \
		s!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g; \
		s!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g; \
		' /usr/local/apache2/conf/httpd.conf \

```
https://github.com/docker-library/httpd/blob/63cd0ad57a12c76ff70d0f501f6c2f1580fa40f5/2.4/Dockerfile

**Comment by md5** [comment]
In addition to what @thaJeztah said about logging being changed explicitly to do things "the Docker way", my guess is that the lack of sourcing of `/etc/apache2/envvars` is not intentional, just overlooked.

Normally the sourcing of `envvars` happens in the `apache2` init script, but the `php:apache` image doesn't use the init script.

If sourcing of `/etc/apache2/envvars` were introduced, we'd need to be careful that doing so didn't cause any breaking changes based on the current content of that file. Here's what it currently has it in by default:

```console
$ docker run --rm php:apache grep -vE '^$|^#' /etc/apache2/envvars
unset HOME
if [ "${APACHE_CONFDIR##/etc/apache2-}" != "${APACHE_CONFDIR}" ] ; then
	SUFFIX="-${APACHE_CONFDIR##/etc/apache2-}"
else
	SUFFIX=
fi
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
export APACHE_PID_FILE=/var/run/apache2/apache2$SUFFIX.pid
export APACHE_RUN_DIR=/var/run/apache2$SUFFIX
export APACHE_LOCK_DIR=/var/lock/apache2$SUFFIX
export APACHE_LOG_DIR=/var/log/apache2$SUFFIX
export LANG=C
export LANG
```

**Comment by leftyhitchens** [comment]
@thaJeztah is sending all logs to STDOUT generally considered a best practice when working with docker containers?

**Comment by thaJeztah** [comment]
in general, but of course, there could be other use-cases, you don't set up logging inside the container and collect logs outside the container. The default logging of Docker is not the best solution for large-volume logging, but different logging drivers were recently added (and a couple of other ones proposed )

see the `--log-driver` option for currently available options; https://docs.docker.com/reference/run/

and a search in the Docker issue tracker will give you some drivers that are currently being worked on :)

**Comment by leftyhitchens** [comment]
@thaJeztah thanks for the helpful information regarding logging. In reference to @md5 comment in the apache2-foreground script: https://github.com/docker-library/php/blob/master/5.4/apache/apache2-foreground adding:

```
exec apache2ctl -DFOREGROUND
```
would source the envvars by default is there any reason why that might not be a good idea?

**Comment by yosifkit** [comment]
@leftyhitchens, I had not realized that `apache2ctl` would run in the foreground.  Are there other side effects that running this way would add?  Would it break any of the current users?

**Comment by thaJeztah** [comment]
@yosifkit I think I've seen a discussion around using apachectl somewhere but I couldn't find it :'( perhaps @tianon remembers...

**Comment by leftyhitchens** [comment]
@yosifkit according to apache's [documentation](http://httpd.apache.org/docs/2.2/programs/apachectl.html) apachectl is just a pass through for the httpd binary specifically setting the envvars before calling the base binary with the specified arguments. As to whether this would impact existing users I cannot imagine how; either the envvars was not sourced in which case they are not using any of the vars in their apache configuration or they have manually sourced the file in which case there should be no general impact to sourcing them twice.

**Comment by yosifkit** [comment]
Nice, sounds good to me.  What do you think, @tianon?  tl;dr: `s/ apache2/ apache2ctl/`

**Comment by tianon** [comment]
To @md5's point, it was actually intentional not to read `envvars` because it seemed pretty silly to track and use these files since they are generally an `init.d` specific thing and since Docker itself can track environment variables (which are then even easier/trivial to override at runtime).  Additionally, since it made sense to provide our own simplified default configuration, the justification for trying to source this file seemed weak, and I'm sorry to say I'm still not convinced.  Is there anything specific this file provides that can't already be achieved by some reasonably simple means?

**Comment by kojiromike** [comment]
At some point in the past the official PHP containers did respect envvars, at least as far as `APACHE_RUN_(USER|GROUP)` were concerned. That enabled solutions like http://serverfault.com/a/652852/72728 to work. Since that has stopped working, I'm updating [my script](https://github.com/kojiromike/docker-magento/blob/master/apache/start_safe_perms) to directly modify the `/etc/apache2/apache2.conf` in the container at start time.

However, this conversation makes me think I'm supposed to be able to do it by setting environment variables before apache2ctl starts. That doesn't quite make sense for these APACHE_RUN_* variables – they appear to be hardcoded into apache2.conf. Am I missing something?

**Comment by tianon** [comment]
Hello @tianon from the past -- it turns out you did not foresee the thought of users bringing existing Apache configuration fragments and dropping them into Docker as-is being a reasonable use case.

As I've stated over in https://github.com/docker-library/php/pull/231, I do now believe it is worth considering sourcing the `envvars` file from the `apache2-foreground` script (likely via that `apache2ctl` bit mentioned earlier, assuming it has no other side effects like staying resident and preventing us from properly becoming PID 1).

**Comment by chrissound** [comment]
This still seems to be an an issue on `php:5.6-apache-stretch`, in that $_ENV doesn't have the variables when run via apache, but the php cil does?

**Comment by tianon** [comment]
5.6 has been completely unsupported since e9320fdb752edb2fb5d1be8412172f5c78255a45 (on Feb 1), but this issue doesn't actually have anything to do with `$_ENV`, but rather has to do with Apache's own environment variables (such as `APACHE_RUN_USER`) used within Apache's configuration.
