### ISSUE TITLE
Fail to allocate port when running with arbitrary user

### ISSUE THREAD

**Issue by rcsilva83** [docker-library/php#980]
Hi!

When I run the following command:

`docker run -it --rm -u 1000 -p 8080:80 php:7.2-apache`

I get the following error:

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
```
This issue is getting in the way of running my app on Kubernetes.

Thanks!

**Comment by wglambert** [comment]
For running the Apache variants as an arbitrary user, there are several choices:

-	If your kernel [is version 4.11 or newer](https://github.com/moby/moby/issues/8460#issuecomment-312459310), you can add `--sysctl net.ipv4.ip_unprivileged_port_start=0` and then `--user` should work as it does for FPM.
-	If you adjust the Apache configuration to use an "unprivileged" port (greater than 1024 by default), then `--user` should work as it does for FPM regardless of kernel version.
-	Otherwise, setting `APACHE_RUN_USER` and/or `APACHE_RUN_GROUP` should have the desired effect (for example, `-e APACHE_RUN_USER=daemon` or `-e APACHE_RUN_USER=#1000` -- see [the Apache `User` directive documentation for details on the expected syntax](https://httpd.apache.org/docs/2.4/mod/mod_unixd.html#user)).

https://github.com/docker-library/docs/tree/master/php#running-as-an-arbitrary-user

See a working example here https://github.com/docker-library/php/issues/94#issuecomment-353673925

**Comment by rcsilva83** [comment]
Hi, @wglambert !

Thanks for your reply and I'm sorry I didn't find this doc.

Before posting, I've already tried `-e APACHE_RUN_USER=#1000` but I've got the same problem.

As for `--sysctl net.ipv4.ip_unprivileged_port_start=0` option I can't use it because I have no guaranties about the kernel version.

So my only option (and the one I like most) is to run Apache on an "unprivileged" port. I couldn't find any "port number parameter", so I guess I'll have to edit config files, right?

PS: I think it'd be useful to to have such parameter. Can I open a feature request?

**Comment by wglambert** [comment]
This comment seems like it suits your needs https://github.com/docker-library/php/issues/94#issuecomment-320695125
```dockerfile
FROM php:7.0-apache
ENV PORT 80
ENTRYPOINT []
CMD sed -i "s/80/$PORT/g" /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf && docker-php-entrypoint apache2-foreground
```

**Comment by rcsilva83** [comment]
Thank you very much
